<?php
require_once __DIR__ . '/../config/helpers.php';
$user=require_auth(); require_page_access($user,'customers');
$method=$_SERVER['REQUEST_METHOD']; $resource=$_GET['resource']??'orders'; $id=trim((string)($_GET['id']??'')); $action=$_GET['action']??'';
if($resource==='sites'){
 if($method==='GET'){ $cid=trim((string)($_GET['customerId']??'')); $s=db()->prepare('SELECT * FROM customer_sites WHERE (? = \'\' OR customer_id=?) ORDER BY name');$s->execute([$cid,$cid]);json_out($s->fetchAll()); }
 if($method==='POST'){ $b=body();$cid=trim((string)($b['customerId']??''));$name=trim((string)($b['name']??''));if(!$cid||!$name)json_error('Customer and site name are required.');$n=uuid();db()->prepare('INSERT INTO customer_sites(id,customer_id,name,location,site_type) VALUES(?,?,?,?,?)')->execute([$n,$cid,$name,$b['location']??null,$b['siteType']??'WORKSHOP']);json_out(['id'=>$n],201); }
}
if($resource==='staff'){
 if($method==='GET'){ $cid=trim((string)($_GET['customerId']??''));$s=db()->prepare('SELECT ws.*,cs.name site_name FROM customer_workshop_staff ws LEFT JOIN customer_sites cs ON cs.id=ws.site_id WHERE (?=\'\' OR ws.customer_id=?) ORDER BY ws.name');$s->execute([$cid,$cid]);json_out($s->fetchAll()); }
 if($method==='POST'){ $b=body();$cid=trim((string)($b['customerId']??''));$name=trim((string)($b['name']??''));if(!$cid||!$name)json_error('Customer and staff name are required.');$n=uuid();db()->prepare('INSERT INTO customer_workshop_staff(id,customer_id,site_id,name,phone,email,role,specialty) VALUES(?,?,?,?,?,?,?,?)')->execute([$n,$cid,$b['siteId']??null,$name,$b['phone']??null,$b['email']??null,$b['role']??'TECHNICIAN',$b['specialty']??null]);json_out(['id'=>$n],201); }
}
if($resource==='orders'){
 if($method==='GET'){ $cid=trim((string)($_GET['customerId']??''));$s=db()->prepare("SELECT wo.*,c.name customer_name,m.model machine_model,cs.name site_name,ws.name assigned_customer_staff_name,cc.contract_number FROM workshop_work_orders wo JOIN customers c ON c.id=wo.customer_id LEFT JOIN machines m ON m.id=wo.machine_id LEFT JOIN customer_sites cs ON cs.id=wo.site_id LEFT JOIN customer_workshop_staff ws ON ws.id=wo.assigned_customer_staff_id LEFT JOIN customer_contracts cc ON cc.id=wo.contract_id WHERE (?='' OR wo.customer_id=?) ORDER BY CASE WHEN wo.status IN ('OPEN','DIAGNOSING','IN_PROGRESS','ESCALATED_TO_BELM') THEN 0 ELSE 1 END, wo.created_at DESC");$s->execute([$cid,$cid]);json_out($s->fetchAll()); }
 if($method==='PUT' && $id && $action==='status'){ $b=body();$status=strtoupper(trim((string)($b['status']??'')));$allowed=['OPEN','ASSIGNED','DIAGNOSING','WAITING_PARTS','IN_PROGRESS','ESCALATED_TO_BELM','TESTING','COMPLETED','CANCELLED'];if(!in_array($status,$allowed,true))json_error('Invalid work order status.');$old=db()->prepare('SELECT status FROM workshop_work_orders WHERE id=?');$old->execute([$id]);$from=$old->fetchColumn();if($from===false)json_error('Work order not found.',404);db()->prepare("UPDATE workshop_work_orders SET status=?, diagnosis=COALESCE(?,diagnosis), work_done=COALESCE(?,work_done), completed_at=CASE WHEN ?='COMPLETED' THEN NOW() ELSE completed_at END, updated_at=NOW() WHERE id=?")->execute([$status,$b['diagnosis']??null,$b['workDone']??null,$status,$id]);db()->prepare('INSERT INTO workshop_work_order_history(id,work_order_id,event_type,from_value,to_value,actor_name,note) VALUES(?,?,?,?,?,?,?)')->execute([uuid(),$id,'STATUS',$from,$status,$user['name'],$b['note']??null]);json_out(['ok'=>true]); }
 if($method==='POST' && $id && $action==='escalate'){ $o=db()->prepare('SELECT * FROM workshop_work_orders WHERE id=?');$o->execute([$id]);$wo=$o->fetch();if(!$wo)json_error('Work order not found.',404);if($wo['belm_service_request_id'])json_error('This work order is already escalated to BELM.');$sr=uuid();db()->beginTransaction();try{db()->prepare("INSERT INTO service_requests(id,customer_id,machine_id,service_type,description,status,priority,origin,created_at,updated_at) VALUES(?,?,?,?,?,'OPEN',?,'CUSTOMER_WORKSHOP',NOW(),NOW())")->execute([$sr,$wo['customer_id'],$wo['machine_id'],$wo['job_type'],'Escalated from customer workshop '.$wo['work_order_number'].': '.$wo['description'],$wo['priority']]);db()->prepare("UPDATE workshop_work_orders SET status='ESCALATED_TO_BELM',belm_service_request_id=?,updated_at=NOW() WHERE id=?")->execute([$sr,$id]);db()->prepare('INSERT INTO workshop_work_order_history(id,work_order_id,event_type,from_value,to_value,actor_name,note) VALUES(?,?,?,?,?,?,?)')->execute([uuid(),$id,'ESCALATED',$wo['status'],'ESCALATED_TO_BELM',$user['name'],'Escalated to BELM service team']);db()->commit();}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();throw $e;}json_out(['ok'=>true,'serviceRequestId'=>$sr]); }
}
json_error('Unsupported workshop operation.',405);
