(function(){'use strict';
 const active=String(localStorage.getItem('belm_active_account_type')||'').toLowerCase(),activeKey={customer:'belm_customer_token',technician:'belm_tech_token',admin:'belm_admin_token',operator:'belm_operator_token'}[active]||'',token=[activeKey,'belm_admin_token','belm_tech_token','belm_customer_token','belm_operator_token'].filter((v,i,a)=>v&&a.indexOf(v)===i).map(k=>localStorage.getItem(k)||'').find(Boolean)||'';if(!token){location.replace('/login');return}
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function decode(v){try{let r=(v.split('.')[1]||'').replace(/-/g,'+').replace(/_/g,'/');r+='='.repeat((4-r.length%4)%4);return JSON.parse(decodeURIComponent(Array.from(atob(r)).map(c=>'%'+c.charCodeAt(0).toString(16).padStart(2,'0')).join('')))}catch(_){return{}}}const s=decode(token);
 const staff={'Super Admin':'super_admin','Workshop Manager':'workshop_manager','Engineer':'workshop_manager','Technician':'technician','Procurement':'procurement','Store Keeper':'store_keeper','Registration & Sales':'registration_sales','Finance / Accounts':'finance_accounts','Bank Controller':'bank_controller','System Coordinator':'system_coordinator'};
 const customer={owner:'customer_admin',admin:'customer_admin',customer_admin:'customer_admin',workshop_manager:'workshop_manager',technician:'technician',operator:'operator',procurement:'procurement',store_keeper:'store_keeper',accounts:'accounts',finance:'accounts',accountant:'accounts'};
 const isCustomer=s.type==='customer'||s.type==='operator',role=isCustomer?(s.type==='operator'?'operator':(customer[String(s.customerRole||(s.actorType==='owner'?'owner':'')).toLowerCase()]||'customer_admin')):(staff[String(s.roleName||'')]||'super_admin');
 const labels={super_admin:'BELM Super Admin',workshop_manager:'Workshop Manager',technician:'Technician',operator:'Operator',procurement:'Procurement',store_keeper:'Store Keeper',registration_sales:'Registration & Sales',finance_accounts:'Finance / Accounts',accounts:'Finance / Accounts',bank_controller:'Bank Controller',system_coordinator:'System Coordinator',customer_admin:'Customer Administration'};
 const withReturn=(href,back='/role-reports/')=>{try{const u=new URL(href,location.origin);if(u.origin!==location.origin)return href;if(!u.searchParams.has('returnTo'))u.searchParams.set('returnTo',back);return u.pathname+u.search+u.hash}catch(_){return href}};
 const c=(tag,title,desc,href)=>({tag,title,desc,href:withReturn(href)}),section=(title,note,cards)=>({title,note,cards});
 const customerMaps={
  customer_admin:[section('Company Operations','Full company reports, still separated from BELM internal Bank and Spare Sales.',[c('MACHINES','Machine & Workshop Reports','Checklist, fuel, operator, technician, Job Card, service and breakdown records for this customer.','/portal/dashboard?view=machines'),c('ANALYSIS','Company Analysis','Cross-department customer operational analysis.','/general-analysis/'),c('FINANCE','Finance Reports','Invoices, proforma, payments, expenses, VAT, petty cash and audit.','/customer-finance/')]),section('Department Reports','Open the detailed department records.',[c('PROCUREMENT','Procurement Records','Purchase requests, orders, proforma and deliveries.','/customer-procurement-workspace/?view=records'),c('STORE','Store Audit','Stock movements, issues, returns and tools.','/customer-store-audit/'),c('AUDIT','Finance Audit Logs','Transaction and finance change history.','/customer-finance-workspace/?view=audit')])],
  workshop_manager:[section('Technical Reports','Workshop Manager receives the full technical chain.',[c('WORKSHOP','Machine & Job Card Reports','Checklist, operator, technician, Job Card, service and breakdown reports owned by Customer Workshop.','/customer-workshop-manager/'),c('ANALYSIS','Technical Analysis','Customer workshop performance and maintenance analysis.','/general-analysis/?module=workshop'),c('WORKFLOW','Active Job Cards','Open, diagnosis, waiting spare, testing and completed work.','/customer-workshop/?actor=customer')]),section('Supporting Departments','Only records needed to coordinate maintenance.',[c('PROCUREMENT','Procurement Status','Track parts requested for maintenance.','/customer-procurement-workspace/?view=records'),c('STORE','Store / Tools','Stock and tools supporting workshop work.','/customer-store-dashboard/')])],
  technician:[section('My Technical Reports','Technician reports focus on assigned machines and work performed.',[c('MACHINES','Machine Reports','Checklist, technician/maintenance, Job Card, service and breakdown history for assigned work.','/portal/dashboard?view=machines'),c('JOBS','My Job Cards','Diagnosis, repair, testing and completion records.','/technician-job-cards/'),c('DASHBOARD','Technician Dashboard','Assigned machines and report actions.','/concept-dashboards/02-technician/')])],
  operator:[section('Machine Operation Reports','Operator sees only day-to-day machine operation records.',[c('OPERATOR','Operator & Checkup Reports','Daily updates, operator reports, fuel and service-related machine records.','/customer-operator-dashboard/'),c('MACHINES','My Machines','Open daily check, fuel usage and problem reporting.','/customer-operator-dashboard/'),c('ANALYSIS','Machine Analysis','Operational condition and usage analysis.','/general-analysis/?module=operator')])],
  procurement:[section('Procurement Reports','Purchasing reports do not expose BELM Spare Sales inventory.',[c('PURCHASE','Purchase Records','Requests, purchase records and current procurement status.','/customer-procurement-workspace/?view=records'),c('PROFORMA','Pending Proforma','Supplier proforma records awaiting action.','/customer-procurement-workspace/?view=proforma'),c('ORDERS','Purchase Orders','Orders placed and their status.','/customer-procurement-workspace/?view=orders'),c('DELIVERY','Delivery Tracking','Expected and completed deliveries.','/customer-procurement-workspace/?view=delivery'),c('ANALYSIS','Procurement Analysis','Department purchasing analysis.','/general-analysis/?module=procurement#procurement-analysis')])],
  store_keeper:[section('Store Reports','Customer Store remains separate from BELM Spare Sales.',[c('INVENTORY','Inventory Reports','Stock balance, issues, shortages and store-linked records.','/customer-store/'),c('AUDIT','Stock Audit','Customer stock movement audit.','/customer-store-audit/'),c('TOOLS','Tools Register','Tool issue, return, condition and overdue records.','/customer-tools-register/'),c('ANALYSIS','Store Analysis','Inventory movement and shortage analysis.','/general-analysis/?module=store#store-analysis')])],
  accounts:[section('Finance Reports','Finance sees company financial records; Bank Controller remains BELM-only.',[c('SALES','Invoices & Proforma','Customer sales documents.','/customer-sales-documents/'),c('PAYMENTS','Payments & Receipts','Payment and receipt history.','/customer-finance-workspace/?view=payments'),c('EXPENSES','Expenses','Company expense records.','/customer-finance-workspace/?view=expenses'),c('PETTY CASH','Petty Cash','Petty cash movement and supporting entries.','/customer-petty-cash/'),c('VAT','VAT / Tax','VAT summary and tax records.','/customer-finance-workspace/?view=vat'),c('AUDIT','Audit Logs','Finance transaction change history.','/customer-finance-workspace/?view=audit'),c('ANALYSIS','Financial Analysis','Customer financial performance.','/general-analysis/?module=finance#finance-analysis')])]
 };
 const belmMaps={
  super_admin:[section('Management Reports','Consolidated visibility across BELM departments.',[c('ALL DEPARTMENTS','Management Overview','Finance, workforce, service and department performance.','/reports-manager/?module=reports'),c('WORKSHOP','Workshop Analysis','Job Cards, technicians, repair and maintenance performance.','/workshop-analysis/?actor=admin&module=reports'),c('CUSTOMERS','Customer & Machine Reports','Customer companies, machines and operational records.','/customers-manager/?module=reports')]),section('Commercial & Control','Department-level reports.',[c('PROCUREMENT','Procurement Reports','Purchases, orders, suppliers and deliveries.','/belm-procurement/?view=reports&module=procurement'),c('STORE','Inventory Audit','BELM stock, issues and inventory audit.','/spare-parts-manager/?view=audit&module=inventory'),c('FINANCE','Finance Reports','Invoices, payments, expenses, proforma and receipts.','/billing-manager/?module=finance'),c('BANK','Bank Audit','Bank balances, withdrawals and approval trail.','/bank-controller/?module=bank'),c('SYSTEM','Activity / Audit','Role activity and system accountability.','/reports-manager/?view=activity&module=reports')])],
  workshop_manager:[section('Technical Department Reports','Workshop-owned operational reporting.',[c('WORKSHOP','Workshop Analysis','Job Cards, diagnosis, testing, completion and technician load.','/workshop-analysis/?actor=admin&module=workshop'),c('JOB CARDS','Job Card Records','Open through completed maintenance work.','/breakdown-workflow/?actor=admin&view=job-cards&module=workshop'),c('MACHINES','Machine History','Machine service and report history.','/reports-manager/?module=workshop')])],
  technician:[section('My Reports','Only reports for machines and Job Cards assigned to this BELM Technician.',[
    c('CHECKLIST','Checklist Report','Daily, inspection and machine check-up records.','/tech?view=machines&reportCategory=checklists'),
    c('DIAGNOSIS','Diagnosis Report','Diagnosis / inspection, new or repeated issue, findings, root cause and solution from assigned Job Cards.','/breakdown-workflow/?actor=technician&view=diagnosis'),
    c('OPERATOR','Operator Report','Operator messages, daily condition and reported machine issues.','/tech?view=machines&reportCategory=operator'),
    c('FUEL','Fuel Report','Fuel quantity, cost and consumption records.','/tech?view=machines&reportCategory=fuel'),
    c('JOB CARD','Job Card Reports','Assigned, active and completed Job Card records.','/tech?view=machines&reportCategory=job-cards'),
    c('MAINTENANCE','Maintenance Report','Service and maintenance history.','/tech?view=machines&reportCategory=maintenance')
  ])],
  procurement:[section('Procurement Reports','Purchasing and supplier performance.',[c('PURCHASE','Purchase Reports','Procurement request and purchase records.','/belm-procurement/?view=reports&module=procurement'),c('ANALYSIS','Department Analysis','Procurement activity analysis.','/belm-procurement/?view=analysis&module=procurement'),c('ORDERS','Purchase Orders','Order status and supplier references.','/belm-procurement/?view=orders&module=procurement'),c('DELIVERY','Delivery Tracking','Expected and received deliveries.','/belm-procurement/?view=delivery&module=procurement')])],
  store_keeper:[section('Store Reports','BELM inventory reporting.',[c('INVENTORY','Inventory Reports','Stock balance, stock in/out and spare usage.','/reports-manager/?view=inventory&module=inventory'),c('AUDIT','Stock Audit','Inventory change and movement audit.','/spare-parts-manager/?view=audit&module=inventory'),c('SHORTAGE','Low Stock','Shortage and reorder attention list.','/spare-parts-manager/?view=low-stock&module=inventory'),c('TOOLS','Tools Register','Tool issue and return records.','/spare-parts-manager/?view=tools&module=inventory')])],
  registration_sales:[section('Registration & Sales Reports','Customer onboarding and commercial activity.',[c('CUSTOMERS','Customer Reports','Registered customers, machines and service activity.','/reports-manager/?module=registration'),c('REGISTRATION','Registration Records','Applications and approvals.','/admin-applications/?module=registration'),c('CONTRACTS','Contracts & Service','Customer contracts and service coverage.','/contracts-workshops/?module=registration')])],
  finance_accounts:[section('Finance Reports','Billing and financial accountability.',[c('OVERVIEW','Finance Overview','Invoice, payment, expense, proforma and receipt totals.','/billing-manager/?module=finance'),c('INVOICES','Invoices','Invoice records.','/billing-manager/?tab=invoices&module=finance'),c('PAYMENTS','Payments','Payment records.','/billing-manager/?tab=payments&module=finance'),c('EXPENSES','Expenses','BELM company expenses.','/billing-manager/?tab=expenses&module=finance'),c('PROFORMA','Proforma','Proforma records.','/billing-manager/?tab=proformas&module=finance'),c('RECEIPTS','Receipts','Official receipt records.','/billing-manager/?tab=receipts&module=finance')])],
  bank_controller:[section('Bank Control Reports','Bank-only financial control; customer finance workspaces are not exposed.',[c('BANK','Bank Accounts','Current bank balances and account records.','/bank-controller/?module=bank'),c('WITHDRAWALS','Withdrawals','Withdrawal records and approvals.','/bank-controller/?module=bank#withdrawalRows'),c('AUDIT','Bank Edit Audit','Protected account edit trail.','/bank-controller/?module=bank#bankEditAuditPanel')])],
  system_coordinator:[section('System Control Reports','Access, configuration and accountability.',[c('SETTINGS','System Settings','Portal configuration and module controls.','/settings-manager/'),c('USERS','Users & Roles','Access assignment and role configuration.','/roles-manager/?module=roles-users'),c('NOTIFICATIONS','Notification Configuration','Email/WhatsApp/SMS and notification controls.','/coordinator/notifications/?module=settings')])]
 };
 const groups=(isCustomer?customerMaps:belmMaps)[role]||[];document.getElementById('title').textContent=(labels[role]||'My Role')+' Reports';document.getElementById('scope').textContent=(isCustomer?'CUSTOMER · ':'BELM · ')+(labels[role]||role.replaceAll('_',' '));document.getElementById('subtitle').textContent='Only reports needed by '+(labels[role]||role.replaceAll('_',' '))+' are placed in this menu.';
 document.getElementById('content').innerHTML=groups.length?groups.map(g=>`<section class="section"><h2>${esc(g.title)}</h2><p>${esc(g.note||'')}</p><div class="grid">${g.cards.map(x=>`<a class="card" href="${esc(x.href)}"><span class="tag">${esc(x.tag)}</span><h3>${esc(x.title)}</h3><p>${esc(x.desc)}</p><strong>Open report →</strong></a>`).join('')}</div></section>`).join(''):'<div class="notice">No report menu is assigned to this role.</div>';document.getElementById('refresh').onclick=()=>location.reload();
})();
