(()=>{
  const modeStyle=document.createElement('style');modeStyle.textContent=`.operating-model-selector{grid-column:1/-1;display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:14px;border:1px solid #2a638d;border-radius:16px;background:#071d32}.operating-model-selector .button-controller-head{grid-column:1/-1}.operating-model-selector .button-controller-head b{display:block;color:#fff;font-size:13px}.operating-model-selector .button-controller-head span{color:#9fb5c7;font-size:10px}.model-option{display:grid;gap:5px;min-height:88px;padding:14px;border:1px solid #315f7f!important;border-radius:13px;background:#0b2948!important;color:#fff!important;text-align:left;cursor:pointer}.model-option b{font-size:12px}.model-option small{color:#9fb5c7!important;line-height:1.45}.model-option.active{border:2px solid var(--belm-gold,#ffc21c)!important;box-shadow:0 0 0 3px rgba(255,194,28,.12)}.model-option.active b{color:var(--belm-gold,#ffc21c)}.model-option:disabled{opacity:.48;cursor:not-allowed}@media(max-width:620px){.operating-model-selector{grid-template-columns:1fr}}`;document.head.appendChild(modeStyle);
  const templateGrid=document.querySelector('.template-grid');
  if(templateGrid&&!templateGrid.querySelector('[data-general-report-centre]'))templateGrid.insertAdjacentHTML('afterbegin','<a class="role-template preview-link" data-general-report-centre href="/coordinator/general-report/"><b>General Report Centre</b><span>Checklist, Operator, Fuel, Job Card, Maintenance, Procurement and Finance reports with From–To date control.</span><strong>Open General Reports →</strong></a>');
  const token=localStorage.getItem('belm_admin_token');
  if(!token){location.replace('/login');return}
  let user=null;try{user=JSON.parse(localStorage.getItem('belm_admin_user')||'null')}catch(_){}
  const role=String(user?.role||'').toLowerCase();
  if(role!=='super admin'&&user?.allowedPages!==null){location.replace('/belm-workshop/');return}
  let all=[];
  const deptButton=document.getElementById('belmDepartmentsButton');
  deptButton?.addEventListener('click',()=>location.assign('/coordinator/departments/'));
  const box=document.getElementById('customers'),alertBox=document.getElementById('alert');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function api(path,opt={}){const r=await fetch('/api'+path,{...opt,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(opt.headers||{})},cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
  function buttonState(f,key,def){return f?.machineCardButtons?.operator?.[key]||def}
  function stateOptions(value){return ['enabled','disabled','hidden'].map(x=>`<option value="${x}" ${x===value?'selected':''}>${x==='enabled'?'Enabled':x==='disabled'?'Disabled':'Hidden / Removed'}</option>`).join('')}
  const departmentLabels={administration:'Administration',technical:'Technical / Workshop',operator:'Machine Operator',procurement:'Procurement',store:'Store / Inventory',finance:'Finance / Accounts',generalReport:'General Report'};
  function departmentState(c,key){return c?.departmentStates?.[key]==='REMOVED'?'REMOVED':'ENABLED'}
  function departmentOptions(value){return `<option value="ENABLED" ${value==='ENABLED'?'selected':''}>Added / Enabled</option><option value="REMOVED" ${value==='REMOVED'?'selected':''}>Removed</option>`}
  function technicianEntitled(c){return departmentState(c,'technical')==='ENABLED' && c?.coordinatorFeatures?.technicianDashboard===true}
  function render(){
    const q=document.getElementById('search').value.toLowerCase().trim();
    const rows=all.filter(x=>!q||`${x.name} ${x.email}`.toLowerCase().includes(q));
    box.innerHTML=rows.length?rows.map(c=>{
      const f=c.coordinatorFeatures||{},entitled=technicianEntitled(c),customerManaged=Boolean(c.selfServiceEnabled&&entitled);
      const modeText=customerManaged?'CUSTOMER SELF-MANAGED WORKSHOP':'BELM MANAGED SERVICE';
      return `<article class="customer" data-id="${esc(c.id)}">
        <div class="customer-main"><h3>${esc(c.name)}</h3><small>${esc(c.email||'')} · ${esc(c.phone||'')}</small><div><span class="mode ${customerManaged?'independent':'connected'}">${modeText}</span></div></div>
        <div class="operating-model-selector"><div class="button-controller-head"><b>Operating Model</b><span>Select who owns daily maintenance and Job Card assignment.</span></div><button type="button" data-operating-mode="BELM_MANAGED" class="model-option ${customerManaged?'':'active'}"><b>BELM Managed</b><small>BELM Technical Department manages maintenance and assigns BELM Technicians.</small></button><button type="button" data-operating-mode="CUSTOMER_MANAGED" class="model-option ${customerManaged?'active':''}" ${!entitled?'disabled title="Enable Technical Department and Technician Dashboard first."':''}><b>Customer Self-Managed</b><small>Customer manages its workshop, technicians, store and internal Job Cards; BELM joins only by support request.</small></button></div>
        <div class="switches"><label class="toggle"><input type="checkbox" data-feature="invoiceSystem" ${f.invoiceSystem?'checked':''}> Invoice System</label><label class="toggle"><input type="checkbox" data-feature="proformaSystem" ${f.proformaSystem?'checked':''}> Proforma System</label><label class="toggle"><input type="checkbox" data-feature="operatorDashboard" ${f.operatorDashboard!==false?'checked':''}> Machine Operator Dashboard</label><label class="toggle"><input type="checkbox" data-feature="technicianDashboard" ${f.technicianDashboard!==false?'checked':''}> Technician Dashboard</label></div>
        <div class="department-controller"><div class="button-controller-head"><b>Customer Department Controller</b><span>Add / Remove access only · workflow data is preserved</span></div>
          ${Object.entries(departmentLabels).map(([key,label])=>`<label>${label}<select data-department-key="${key}">${departmentOptions(departmentState(c,key))}</select></label>`).join('')}
        </div>
        <div class="button-controller"><div class="button-controller-head"><b>Machine Card Button Controller</b><span>Operator Dashboard · Enabled / Disabled / Hidden</span></div>
          <label>View Report<select data-button-key="report">${stateOptions(buttonState(f,'report','enabled'))}</select></label>
          <label>Alert Report<select data-button-key="operationCard">${stateOptions(buttonState(f,'operationCard','enabled'))}</select></label>
          <label>Hand Over Report<select data-button-key="handOverReport">${stateOptions(buttonState(f,'handOverReport','enabled'))}</select></label>
        </div>
      </article>`
    }).join(''):'<div class="empty">No matching customer.</div>';
    wire();
  }
  async function confirmEdit(message){if(!window.belmConfirmEdit)return null;return await window.belmConfirmEdit({title:'Coordinator change',message})}
  function currentPayload(c){const f=c.coordinatorFeatures||{};return{invoiceSystem:!!f.invoiceSystem,proformaSystem:!!f.proformaSystem,operatorDashboard:f.operatorDashboard!==false,technicianDashboard:f.technicianDashboard!==false,machineCardButtons:{operator:{report:buttonState(f,'report','enabled'),operationCard:buttonState(f,'operationCard','enabled'),handOverReport:buttonState(f,'handOverReport','enabled')}}}}
  function wire(){
    box.querySelectorAll('[data-operating-mode]').forEach(button=>button.addEventListener('click',async()=>{const card=button.closest('.customer'),id=card.dataset.id,c=all.find(x=>x.id===id),customerManaged=button.dataset.operatingMode==='CUSTOMER_MANAGED',old=Boolean(c.selfServiceEnabled);if(customerManaged===old)return;button.disabled=true;try{const conf=await confirmEdit(`Change ${c.name} to ${customerManaged?'Customer Self-Managed Workshop':'BELM Managed Service'}. Existing machines, users, Job Cards, reports and financial records will be preserved.`);if(!conf)return;const d=await api(`/customers/${id}/machinery-admin`,{method:'PUT',body:JSON.stringify({serviceProviderEnabled:!customerManaged,editPin:conf.editPin})});c.selfServiceEnabled=Boolean(d.operatingMode==='CUSTOMER_MANAGED');c.operatingMode=d.operatingMode;c.operatingModeLabel=d.operatingModeLabel;render()}catch(e){alertBox.textContent=e.message;alertBox.hidden=false;button.disabled=false}}));
    box.querySelectorAll('input[data-feature]').forEach(inp=>inp.addEventListener('change',async()=>{const card=inp.closest('.customer'),id=card.dataset.id,c=all.find(x=>x.id===id),feature=inp.dataset.feature,desired=inp.checked;inp.disabled=true;try{const conf=await confirmEdit(`Confirm ${desired?'enable':'disable'} ${feature==='belm'?'BELM Service':feature} for ${c.name}. No customer data will be deleted.`);if(!conf){inp.checked=!desired;return}if(feature==='belm'){await api(`/customers/${id}/machinery-admin`,{method:'PUT',body:JSON.stringify({serviceProviderEnabled:desired,editPin:conf.editPin})});c.selfServiceEnabled=!desired}else{const payload=currentPayload(c);payload[feature]=desired;const d=await api(`/customers/${id}/coordinator-features`,{method:'PUT',body:JSON.stringify({...payload,editPin:conf.editPin})});c.coordinatorFeatures=payload;if(d.belmServiceForced)c.selfServiceEnabled=false}render()}catch(e){inp.checked=!desired;alertBox.textContent=e.message;alertBox.hidden=false}finally{inp.disabled=false}}));
    box.querySelectorAll('select[data-department-key]').forEach(sel=>sel.addEventListener('change',async()=>{const card=sel.closest('.customer'),id=card.dataset.id,c=all.find(x=>x.id===id),key=sel.dataset.departmentKey,newState=sel.value,oldState=departmentState(c,key);sel.disabled=true;try{const conf=await confirmEdit(`${newState==='ENABLED'?'Add / enable':'Remove'} ${departmentLabels[key]} for ${c.name}. This changes access only; existing workflow records and history remain stored.`);if(!conf){sel.value=oldState;return}const d=await api(`/customers/${id}/coordinator-departments`,{method:'PUT',body:JSON.stringify({departments:{[key]:newState},editPin:conf.editPin})});c.departmentStates=d.departmentStates;if(d.belmServiceForced)c.selfServiceEnabled=false;render()}catch(e){sel.value=oldState;alertBox.textContent=e.message;alertBox.hidden=false}finally{sel.disabled=false}}));
    box.querySelectorAll('select[data-button-key]').forEach(sel=>sel.addEventListener('change',async()=>{const card=sel.closest('.customer'),id=card.dataset.id,c=all.find(x=>x.id===id),key=sel.dataset.buttonKey,newState=sel.value,oldState=buttonState(c.coordinatorFeatures||{},key,key==='parts'?'disabled':'enabled');sel.disabled=true;try{const conf=await confirmEdit(`Set Operator Machine Card button “${key}” to ${newState.toUpperCase()} for ${c.name}. Hidden only removes it from display; no function or data is deleted.`);if(!conf){sel.value=oldState;return}const payload=currentPayload(c);payload.machineCardButtons.operator[key]=newState;await api(`/customers/${id}/coordinator-features`,{method:'PUT',body:JSON.stringify({...payload,editPin:conf.editPin})});c.coordinatorFeatures=payload;render()}catch(e){sel.value=oldState;alertBox.textContent=e.message;alertBox.hidden=false}finally{sel.disabled=false}}));
  }
  async function load(){alertBox.hidden=true;try{all=await api('/customers/cwm-overview');render()}catch(e){box.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
  document.getElementById('search').oninput=render;document.getElementById('refresh').onclick=load;load();
})();
