(function(){
  const adminToken=localStorage.getItem('belm_tech_token');
  const customerToken=localStorage.getItem('belm_customer_token');
  function payload(t){if(!t)return null;try{const x=t.split('.')[1].replace(/-/g,'+').replace(/_/g,'/');return JSON.parse(decodeURIComponent(Array.from(atob(x)).map(c=>`%${c.charCodeAt(0).toString(16).padStart(2,'0')}`).join('')))}catch{return null}}
  const techPayload=payload(adminToken),customerPayload=payload(customerToken);
  const customerIsTech=String(customerPayload?.roleName||customerPayload?.customerRole||customerPayload?.role||'').toLowerCase()==='technician';
  const token=(techPayload&&String(techPayload.roleName||'').toLowerCase()==='technician')?adminToken:(customerIsTech?customerToken:null);
  if(!token){location.replace('/login');return}
  const params=new URLSearchParams(location.search),machine=params.get('machine')||'';
  let jobs=[],tab='active';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const fmt=v=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString([],{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})};
  const human=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
  function alertMsg(msg,error=false){const b=document.getElementById('alertBox');b.textContent=msg;b.className=`alert${error?' error':''}`;setTimeout(()=>b.classList.add('hidden'),5000)}
  async function api(path,opt={}){const r=await fetch(`/api/breakdown-workflow${path}`,{...opt,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(opt.headers||{})}});const text=await r.text();let d=null;try{d=text?JSON.parse(text):null}catch{}if(!r.ok)throw new Error(d?.error||'Request failed.');return d}
  function stageIndex(stage,status){if(status==='COMPLETED'||stage==='COMPLETED')return 5;if(stage==='TESTING')return 4;if(['REPAIR','PARTS_READY'].includes(stage))return 3;if(['BOSS_APPROVAL','STORE_CHECK','PROCUREMENT','ACCOUNTS'].includes(stage))return 2;if(stage==='DIAGNOSIS')return 2;return 1}
  function processLabel(j){const s=String(j.current_stage||'').toUpperCase();if(['BOSS_APPROVAL','STORE_CHECK','PROCUREMENT','ACCOUNTS'].includes(s))return `Waiting spare / approval · ${human(s)}`;if(s==='TESTING')return 'Repair submitted · Waiting Workshop test';if(s==='COMPLETED')return 'Completed / reference ready';if(s==='REPAIR')return 'Repair in progress';if(s==='DIAGNOSIS')return 'Diagnosis / Technician action';return 'Assigned / waiting to start'}
  function renderSummary(){const active=jobs.filter(j=>j.status!=='COMPLETED').length,done=jobs.filter(j=>j.status==='COMPLETED').length,waiting=jobs.filter(j=>['BOSS_APPROVAL','STORE_CHECK','PROCUREMENT','ACCOUNTS'].includes(String(j.current_stage||'').toUpperCase())).length;document.getElementById('summary').innerHTML=`<div><b>${active}</b><span>Active Job Cards</span></div><div><b>${waiting}</b><span>Waiting spare / approval</span></div><div><b>${done}</b><span>My completed reports</span></div>`}
  function render(){renderSummary();const q=document.getElementById('searchBox').value.toLowerCase().trim();let rows=jobs.filter(j=>tab==='reports'?j.status==='COMPLETED':j.status!=='COMPLETED');if(q)rows=rows.filter(j=>[j.job_card_no,j.title,j.machineLabel,j.customer_name,j.fault_description].join(' ').toLowerCase().includes(q));document.getElementById('jobList').innerHTML=rows.length?rows.map(j=>{const idx=stageIndex(String(j.current_stage||'').toUpperCase(),String(j.case_status||'').toUpperCase());const priority=String(j.priority||'NORMAL').toUpperCase();const report=[j.diagnosis?`<div><span>Diagnosis</span><p>${esc(j.diagnosis)}</p></div>`:'',j.work_done?`<div><span>Work done</span><p>${esc(j.work_done)}</p></div>`:'',j.test_result?`<div><span>Test result</span><p>${esc(j.test_result)}</p></div>`:'',j.completion_note?`<div><span>Completion note</span><p>${esc(j.completion_note)}</p></div>`:''].join('');return `<article class="job-card"><div class="job-head"><div><h2>${esc(j.job_card_no)} · ${esc(j.title)}</h2><small>${esc(j.customer_name)} · ${esc(j.machineLabel)}</small></div><span class="badge ${j.status==='COMPLETED'?'green':priority==='URGENT'?'red':priority==='HIGH'?'yellow':'blue'}">${esc(j.status==='COMPLETED'?'COMPLETED':priority)}</span></div><div class="job-body"><div class="facts"><div class="fact"><span>Issued By</span><b>${esc(j.issued_by_name||'BELM / Customer')}</b></div><div class="fact"><span>Issued</span><b>${esc(fmt(j.issued_at||j.created_at))}</b></div><div class="fact"><span>Due Date</span><b>${esc(j.due_date||'No due date')}</b></div><div class="fact"><span>Spare Requests</span><b>${esc(j.openSpareRequests||0)} open</b></div></div><div class="fault"><b>Job / Fault:</b> ${esc(j.fault_description||j.title)}</div><div class="process"><div class="process-title"><b>${esc(processLabel(j))}</b>${j.blocker_reason?`<span>${esc(j.blocker_reason)}</span>`:''}</div><div class="process-bar">${[1,2,3,4,5].map(n=>`<span class="${n<idx?'done':n===idx?'current':''}"></span>`).join('')}</div></div>${report?`<div class="job-report">${report}</div>`:''}<div class="actions">${j.status!=='COMPLETED'?`<button class="blue" data-report="${esc(j.id)}">Open / Update Job Report</button><button class="yellow" data-spare="${esc(j.id)}">Request Spare</button>`:''}<button class="green" data-pdf="${esc(j.id)}">${j.status==='COMPLETED'?'Download Report PDF':'Download Job Card PDF'}</button></div></div></article>`}).join(''):`<div class="empty">${tab==='reports'?'No completed Job Card reports yet.':'No active Job Cards assigned to you.'}</div>`}
  async function load(){try{const qs=machine?`?machineId=${encodeURIComponent(machine)}`:'';jobs=await api(`/technician-jobs${qs}`);render()}catch(e){document.getElementById('jobList').innerHTML=`<div class="empty">${esc(e.message)}</div>`;alertMsg(e.message,true)}}
  function openReport(id){const j=jobs.find(x=>String(x.id)===String(id));if(!j)return;document.getElementById('reportJobId').value=j.id;document.getElementById('reportTitle').textContent=`${j.job_card_no} · ${j.title}`;document.getElementById('reportDiagnosis').value=j.diagnosis||'';document.getElementById('reportWork').value=j.work_done||'';document.getElementById('reportTest').value=j.test_result||'';document.getElementById('reportNote').value=j.completion_note||'';document.getElementById('reportRepeat').checked=Boolean(Number(j.repeat_issue||0));document.getElementById('reportComplete').checked=false;document.getElementById('reportDialog').showModal()}
  function openSpare(id){const j=jobs.find(x=>String(x.id)===String(id));if(!j)return;document.getElementById('spareJobId').value=j.id;document.getElementById('spareCaseId').value=j.case_id;document.getElementById('spareName').value='';document.getElementById('sparePart').value='';document.getElementById('spareQty').value='1';document.getElementById('spareReason').value='';document.getElementById('spareDialog').showModal()}
  async function downloadPdf(id){try{const r=await fetch(`/api/breakdown-workflow/job-card-pdf/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(e.error||'Could not prepare Job Card PDF.')}const blob=await r.blob(),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`BELM-Job-Card-${id}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}catch(e){alertMsg(e.message,true)}}
  document.getElementById('jobList').addEventListener('click',e=>{const r=e.target.closest('[data-report]'),s=e.target.closest('[data-spare]'),p=e.target.closest('[data-pdf]');if(r)openReport(r.dataset.report);else if(s)openSpare(s.dataset.spare);else if(p)downloadPdf(p.dataset.pdf)});
  document.getElementById('reportForm').addEventListener('submit',async e=>{e.preventDefault();try{const id=document.getElementById('reportJobId').value;await api(`/job-report/${encodeURIComponent(id)}`,{method:'PUT',body:JSON.stringify({diagnosis:document.getElementById('reportDiagnosis').value.trim(),workDone:document.getElementById('reportWork').value.trim(),testResult:document.getElementById('reportTest').value.trim(),completionNote:document.getElementById('reportNote').value.trim(),repeatIssue:document.getElementById('reportRepeat').checked,complete:document.getElementById('reportComplete').checked})});document.getElementById('reportDialog').close();alertMsg('Job Report saved.');await load()}catch(x){alertMsg(x.message,true)}});
  document.getElementById('spareForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/spare',{method:'POST',body:JSON.stringify({caseId:document.getElementById('spareCaseId').value,jobCardId:document.getElementById('spareJobId').value,spareName:document.getElementById('spareName').value.trim(),partNumber:document.getElementById('sparePart').value.trim(),quantity:Number(document.getElementById('spareQty').value||1),unit:document.getElementById('spareUnit').value.trim()||'pcs',reason:document.getElementById('spareReason').value.trim()})});document.getElementById('spareDialog').close();alertMsg('Spare request sent for approval / Procurement.');await load()}catch(x){alertMsg(x.message,true)}});
  document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.close)?.close()));
  document.querySelector('.tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));render()});
  document.getElementById('searchBox').addEventListener('input',render);document.getElementById('refreshButton').addEventListener('click',load);load();
})();