(function(){
  const token=localStorage.getItem('belm_admin_token')||'';
  let adminUser=null;try{adminUser=JSON.parse(localStorage.getItem('belm_admin_user')||'null')}catch{}
  const canManageSuppliers=adminUser?.role==='Super Admin'||adminUser?.allowedPages===null||(Array.isArray(adminUser?.allowedPages)&&adminUser.allowedPages.includes('suppliers'));
  const embedded=new URLSearchParams(location.search).get('embed')==='1'&&window.parent!==window;
  if(!token){location.replace('/login');return}
  if(!embedded){location.replace('/belm-workshop/#procurement');return}
  let data={jobCardRequests:[],inventoryRequests:[],suppliers:[],metrics:{}};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const fmt=v=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString([], {day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})};
  async function api(path,opt={}){const r=await fetch(`/api/belm-procurement${path}`,{...opt,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(opt.headers||{})}});const text=await r.text();let out=null;try{out=text?JSON.parse(text):null}catch{}if(!r.ok)throw new Error(out?.error||`Request failed (${r.status}).`);return out}
  function show(message,error=false){const e=document.getElementById('alertBox');e.textContent=message;e.className=`alert${error?' error':''}`;clearTimeout(show.t);show.t=setTimeout(()=>e.classList.add('hidden'),4500)}
  function statusBadge(status,ordered=false){const s=String(status||'').toUpperCase();if(ordered||s==='ORDERED')return '<span class="badge ordered">ORDERED · WAITING STORE</span>';if(s==='PI_WAITING_ACCOUNTS')return '<span class="badge accounts">WAITING ACCOUNTS / PI</span>';return '<span class="badge">WAITING SOURCING</span>'}
  function supplierMeta(r){if(!r.supplierName&&!r.procurementOrderedAt)return '';return `<div class="order-meta"><b>Supplier:</b> ${esc(r.supplierName||'—')} · <b>Ordered by:</b> ${esc(r.procurementOrderedByName||'—')} · <b>Ordered:</b> ${esc(fmt(r.procurementOrderedAt))}${r.procurementExpectedAt?` · <b>Expected:</b> ${esc(r.procurementExpectedAt)}`:''}${r.procurementSupplierReference?`<br><b>Reference:</b> ${esc(r.procurementSupplierReference)}`:''}${r.procurementNote?`<br>${esc(r.procurementNote)}`:''}</div>`}
  function renderJobs(){const q=document.getElementById('jobQueue'),rows=data.jobCardRequests||[];document.getElementById('jobQueueCount').textContent=rows.length;if(!rows.length){q.innerHTML='<div class="empty">No BELM Job Card spare is waiting for Procurement.</div>';return}q.innerHTML=rows.map(r=>{const ordered=r.status==='ORDERED';const accounts=r.status==='PI_WAITING_ACCOUNTS';return `<article class="proc-card"><div><div class="proc-card-head"><div>${statusBadge(r.status)}<h3>${esc(r.partNumber?`${r.partNumber} — ${r.spareName}`:r.spareName)}</h3></div><b>${esc(r.quantity)} ${esc(r.unit)}</b></div><div class="details"><span><b>Job Card:</b> ${esc(r.jobCardNo||'—')}</span><span><b>Customer:</b> ${esc(r.customerName||'—')}</span><span><b>Machine:</b> ${esc([r.machineBrand,r.machineModel].filter(Boolean).join(' ')||r.machineType||'—')}</span><span><b>Fleet/SN:</b> ${esc(r.fleetNumber||r.serialNumber||r.regNumber||'—')}</span><span><b>Requested by:</b> ${esc(r.requestedByName||'—')}</span><span><b>Requested:</b> ${esc(fmt(r.requestedAt))}</span></div>${supplierMeta(r)}</div><div class="proc-actions">${!ordered?`<button class="primary" data-order="1" data-source="job-card" data-id="${esc(r.id)}" data-label="${esc(r.spareName)}">Mark Ordered</button>`:''}${!accounts&&!ordered?`<button class="accounts" data-accounts="${esc(r.id)}">Send Accounts / PI</button>`:''}${accounts?'<small>Accounts / PI action is pending. Procurement can still mark the order when cleared.</small>':''}${ordered?'<small>Order placed. BELM Store must receive the part and mark Parts Ready before Technician continues.</small>':''}</div></article>`}).join('')}
  function renderInventory(){const q=document.getElementById('inventoryQueue'),rows=data.inventoryRequests||[];document.getElementById('inventoryQueueCount').textContent=rows.length;if(!rows.length){q.innerHTML='<div class="empty">No BELM Inventory purchase request is waiting.</div>';return}q.innerHTML=rows.map(r=>{const ordered=String(r.procurementOrderStatus||'').toUpperCase()==='ORDERED';return `<article class="proc-card"><div><div class="proc-card-head"><div>${statusBadge(r.status,ordered)}<h3>${esc(r.partNumber?`${r.partNumber} — ${r.partName||r.description}`:(r.description||'Spare request'))}</h3></div><b>${esc(r.quantity||1)} PC</b></div><div class="details"><span><b>Customer:</b> ${esc(r.customerName||'BELM stock')}</span><span><b>Machine:</b> ${esc([r.machineBrand,r.machineModel].filter(Boolean).join(' ')||r.machineType||'—')}</span><span><b>Fleet/SN:</b> ${esc(r.fleetNumber||r.serialNumber||r.regNumber||'—')}</span><span><b>Requested by:</b> ${esc(r.requestedByName||'—')}</span><span><b>Current stock:</b> ${esc(r.stockQty??0)}</span><span><b>Requested:</b> ${esc(fmt(r.createdAt))}</span></div>${supplierMeta(r)}</div><div class="proc-actions">${!ordered?`<button class="primary" data-order="1" data-source="inventory" data-id="${esc(r.id)}" data-label="${esc(r.partName||r.description||r.partNumber||'Spare')}">Mark Ordered</button>`:'<small>Order placed. BELM Store/Spare Parts receives it into stock and marks the request fulfilled.</small>'}</div></article>`}).join('')}
  function renderSuppliers(){const box=document.getElementById('supplierRows'),rows=data.suppliers||[];if(!rows.length){box.innerHTML='<div class="empty">No suppliers saved yet.</div>';return}box.innerHTML=rows.map(s=>`<article class="supplier-card">${s.verified?'<span class="verified">VERIFIED</span>':''}<strong>${esc(s.name)}</strong>${s.specialty?`<span>${esc(s.specialty)}</span>`:''}${s.location?`<span>${esc(s.location)}</span>`:''}${s.phone?`<a href="tel:${esc(s.phone)}">${esc(s.phone)}</a>`:''}${s.email?`<a href="mailto:${esc(s.email)}">${esc(s.email)}</a>`:''}${s.website?`<a href="${esc(s.website)}" target="_blank" rel="noopener">Website</a>`:''}</article>`).join('');const manage=document.getElementById('manageSuppliersLink');if(manage&&!canManageSuppliers)manage.hidden=true}
  function fillSuppliers(){const select=document.getElementById('supplierSelect');select.innerHTML='<option value="">Select supplier…</option>'+(data.suppliers||[]).map(s=>`<option value="${esc(s.id)}">${esc(s.name)}${s.verified?' · Verified':''}${s.location?` · ${esc(s.location)}`:''}</option>`).join('')}
  function renderMetrics(){const m=data.metrics||{};document.getElementById('waitingSourcing').textContent=Number(m.waitingSourcing||0);document.getElementById('waitingAccounts').textContent=Number(m.waitingAccounts||0);document.getElementById('orderedCount').textContent=Number(m.ordered||0);document.getElementById('supplierCount').textContent=Number(m.suppliers||0)}
  async function load(){try{data=await api('');renderMetrics();fillSuppliers();renderSuppliers();renderJobs();renderInventory();if(location.hash==='#suppliers')requestAnimationFrame(()=>document.getElementById('suppliers')?.scrollIntoView({block:'start'}))}catch(e){show(e.message,true);document.getElementById('jobQueue').innerHTML=`<div class="empty">${esc(e.message)}</div>`;document.getElementById('inventoryQueue').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
  function openOrder(source,id,label){document.getElementById('orderId').value=id;document.getElementById('orderSource').value=source;document.getElementById('orderTitle').textContent=`Mark Ordered — ${label}`;document.getElementById('supplierSelect').value='';document.getElementById('supplierReference').value='';document.getElementById('expectedAt').value='';document.getElementById('orderNote').value='';document.getElementById('orderError').classList.add('hidden');document.getElementById('orderDialog').showModal()}
  document.addEventListener('click',async e=>{const order=e.target.closest('[data-order]');if(order){openOrder(order.dataset.source||'',order.dataset.id||'',order.dataset.label||'Spare');return}const accounts=e.target.closest('[data-accounts]');if(accounts){const note=prompt('Procurement note to Accounts / PI (optional):')||'';try{await api(`/${encodeURIComponent(accounts.dataset.accounts)}`,{method:'PUT',body:JSON.stringify({source:'job-card',action:'send-accounts',note})});show('Spare sent to Accounts / PI.');await load()}catch(x){show(x.message,true)}}});
  document.getElementById('orderForm').onsubmit=async e=>{e.preventDefault();const error=document.getElementById('orderError');error.classList.add('hidden');try{await api(`/${encodeURIComponent(document.getElementById('orderId').value)}`,{method:'PUT',body:JSON.stringify({source:document.getElementById('orderSource').value,action:'order',supplierId:document.getElementById('supplierSelect').value,supplierReference:document.getElementById('supplierReference').value,expectedAt:document.getElementById('expectedAt').value,note:document.getElementById('orderNote').value})});document.getElementById('orderDialog').close();show('Order saved. BELM Store has been alerted for receipt.');await load()}catch(x){error.textContent=x.message;error.classList.remove('hidden')}};
  document.getElementById('closeOrder').onclick=()=>document.getElementById('orderDialog').close();document.getElementById('cancelOrder').onclick=()=>document.getElementById('orderDialog').close();document.getElementById('refreshButton').onclick=load;document.getElementById('supplierDirectoryButton').onclick=()=>document.getElementById('suppliers')?.scrollIntoView({behavior:'smooth',block:'start'});
  load();
})();
