(function(){'use strict';
  const active=String(localStorage.getItem('belm_active_account_type')||'').toLowerCase(),activeKey={customer:'belm_customer_token',technician:'belm_tech_token',admin:'belm_admin_token',operator:'belm_operator_token'}[active]||'',token=[activeKey,'belm_admin_token','belm_tech_token','belm_customer_token','belm_operator_token'].filter((v,i,a)=>v&&a.indexOf(v)===i).map(k=>localStorage.getItem(k)||'').find(Boolean)||'';
  if(!token){location.replace('/login');return;}
  const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let data={messages:[],recipients:[],customers:[]},filter='inbox';
  async function api(path,opt={}){const r=await fetch('/api/role-communications'+path,{...opt,cache:'no-store',headers:{Authorization:'Bearer '+token,...(opt.body?{'Content-Type':'application/json'}:{})}}),d=await r.json().catch(()=>({}));if(r.status===401){location.replace('/login');throw Error('Session expired.')}if(!r.ok)throw Error(d.error||'Communication request failed.');return d}
  function fmt(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}
  function withReturn(href){try{const u=new URL(href,location.origin);if(u.origin!==location.origin)return href;if(!u.searchParams.has('returnTo'))u.searchParams.set('returnTo','/role-communications/');return u.pathname+u.search+u.hash}catch(_){return href}}
  function note(m,e=false){const n=$('notice');if(!m){n.classList.add('hidden');return}n.textContent=m;n.className='notice'+(e?' error':'')}
  function visible(){return data.messages.filter(m=>filter==='all'||(filter==='sent'?m.isSent:filter==='unread'?!m.isSent&&!m.isRead:filter==='urgent'?!m.isSent&&m.priority==='URGENT':!m.isSent))}
  function stats(){const inbox=data.messages.filter(m=>!m.isSent),sent=data.messages.filter(m=>m.isSent);$('inboxCount').textContent=inbox.length;$('unreadCount').textContent=inbox.filter(m=>!m.isRead).length;$('urgentCount').textContent=inbox.filter(m=>m.priority==='URGENT').length;$('sentCount').textContent=sent.length}
  function render(){const rows=visible();$('messages').innerHTML=rows.length?rows.map(m=>`<article class="msg ${!m.isRead&&!m.isSent?'unread':''} ${String(m.priority||'').toLowerCase()}" data-id="${esc(m.id)}"><div class="msg-head"><div><span class="badge ${String(m.priority||'').toLowerCase()}">${esc(m.priority||'NORMAL')}</span><h3>${esc(m.subject||'Operational message')}</h3></div><small>${esc(fmt(m.createdAt))}</small></div><p>${esc(m.message||'')}</p><div class="meta"><span>${m.isSent?'To':'From'}: ${esc(m.isSent?m.recipientLabel:(m.senderName+' · '+String(m.senderRole||'').replaceAll('_',' ')))}</span>${m.customerName?`<span>Company: ${esc(m.customerName)}</span>`:''}${!m.isRead&&!m.isSent?'<span class="badge">NEW</span>':''}</div>${m.actionUrl?`<a class="open-link" href="${esc(withReturn(m.actionUrl))}">Open related record →</a>`:''}</article>`).join(''):'<div class="empty">No messages in this view.</div>';document.querySelectorAll('.msg[data-id]').forEach(el=>el.onclick=async e=>{if(e.target.closest('a'))return;const m=data.messages.find(x=>String(x.id)===String(el.dataset.id));if(!m||m.isSent||m.isRead)return;try{await api('/'+encodeURIComponent(m.id)+'/read',{method:'PUT'});m.isRead=true;stats();render()}catch(err){note(err.message,true)}})}
  function recipients(){ $('recipient').innerHTML='<option value="">Select role…</option>'+data.recipients.map(r=>`<option value="${esc(r.key)}" data-customer="${r.needsCustomer?'1':'0'}">${esc(r.label)}</option>`).join('');$('customer').innerHTML='<option value="">Select customer…</option>'+data.customers.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join(''); }
  function recipientChanged(){const o=$('recipient').selectedOptions[0],needs=o?.dataset.customer==='1';$('customerLabel').classList.toggle('hidden',!needs);$('customer').required=!!needs;if(!needs)$('customer').value=''}
  async function load(){try{note('');data=await api('');$('actor').textContent=(data.actor?.scope==='BELM'?'BELM · ':'CUSTOMER · ')+(data.actor?.roleLabel||data.actor?.role||'Role');recipients();recipientChanged();stats();render()}catch(e){note(e.message,true);$('messages').innerHTML='<div class="empty">Could not load Role Communication.</div>'}}
  $('filters').onclick=e=>{const b=e.target.closest('button[data-filter]');if(!b)return;filter=b.dataset.filter;document.querySelectorAll('#filters button').forEach(x=>x.classList.toggle('active',x===b));render()};$('recipient').onchange=recipientChanged;$('refresh').onclick=load;$('compose').onsubmit=async e=>{e.preventDefault();const selected=$('recipient').selectedOptions[0];if(!selected?.value)return;const payload={recipient:selected.value,customerId:$('customer').value,priority:$('priority').value,subject:$('subject').value.trim(),message:$('message').value.trim()};try{await api('',{method:'POST',body:JSON.stringify(payload)});$('message').value='';$('subject').value='';$('priority').value='NORMAL';note('Message sent to the selected role.');filter='sent';document.querySelectorAll('#filters button').forEach(x=>x.classList.toggle('active',x.dataset.filter==='sent'));await load()}catch(err){note(err.message,true)}};load();setInterval(()=>{if(!document.hidden)load()},45000);
})();
