(function(){
'use strict';
const token=localStorage.getItem('belm_admin_token')||'';
if(!token){location.replace('/login');return}
let expenses=[],activeFilter='ALL';const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=v=>'TZS '+Number(v||0).toLocaleString('en-TZ',{maximumFractionDigits:2});
function show(msg,error=false){$('alert').textContent=msg;$('alert').className='alert'+(error?' error':'')}
async function api(path,options={}){const r=await fetch('/api'+path,{...options,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token,...(options.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch(_){}if(!r.ok)throw new Error(d?.error||'Request failed');return d}
function today(){return new Date().toISOString().slice(0,10)}
function total(){const q=Number($('quantity').value||0),p=Number($('unitPrice').value||0);$('totalPreview').textContent=money(q*p);return q*p}
function resetForm(){ $('expenseForm').reset();$('expenseId').value='';$('receiptUrl').value='';$('date').value=today();$('quantity').value='1';$('formTitle').textContent='Add Expense';$('saveButton').textContent='Save';$('cancelEdit').classList.add('hidden');$('receiptStatus').textContent='';total();}
function readReceipt(file){return new Promise((resolve,reject)=>{if(!file){resolve(null);return}const isPdf=file.type==='application/pdf';if(!isPdf&&!file.type.startsWith('image/')){reject(new Error('Receipt must be image or PDF.'));return}if(file.size>4*1024*1024){reject(new Error('Receipt must be 4 MB or smaller.'));return}const r=new FileReader();r.onload=()=>resolve({dataUrl:r.result,name:file.name});r.onerror=()=>reject(new Error('Could not read receipt.'));r.readAsDataURL(file)})}
function labelCat(c){return String(c||'OTHER').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase())}
function render(){const q=$('search').value.toLowerCase().trim();const list=expenses.filter(e=>(activeFilter==='ALL'||String(e.category)===activeFilter)&&(!q||[e.category,e.description,e.paymentMethod,e.recordedBy,e.date].join(' ').toLowerCase().includes(q)));$('rows').innerHTML=list.length?list.map(e=>`<tr><td>${esc(e.date||'—')}</td><td><span class="badge">${esc(labelCat(e.category))}</span></td><td>${esc(e.description||'—')}</td><td>${esc(e.quantity??1)}</td><td>${money(e.unitPrice??(Number(e.amount||0)/Number(e.quantity||1)))}</td><td><strong>${money(e.amount)}</strong></td><td>${esc(String(e.paymentMethod||'CASH').replaceAll('_',' '))}</td><td><div class="actions">${e.hasReceipt?`<a class="receipt" href="/api/company-expenses/${encodeURIComponent(e.id)}?action=receipt&download=1&token=${encodeURIComponent(token)}" target="_blank" rel="noopener">Download Receipt</a>`:''}<button class="edit" data-edit="${esc(e.id)}">Edit</button><button class="delete" data-delete="${esc(e.id)}">Delete</button></div></td></tr>`).join(''):'<tr><td colspan="8" class="empty">No payment records found.</td></tr>';$('rows').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editExpense(b.dataset.edit));$('rows').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteExpense(b.dataset.delete))}
function editExpense(id){const e=expenses.find(x=>String(x.id)===String(id));if(!e)return;$('expenseId').value=e.id;$('category').value=e.category||'OTHERS';$('description').value=e.description||'';$('quantity').value=e.quantity??1;$('unitPrice').value=e.unitPrice??(Number(e.amount||0)/Number(e.quantity||1));$('paymentMethod').value=e.paymentMethod||'CASH';$('date').value=e.date||today();$('receiptUrl').value=e.receiptUrl||'';$('receiptStatus').textContent=e.hasReceipt?'Receipt already attached. Upload another file to replace it.':'';$('formTitle').textContent='Edit Expense';$('saveButton').textContent='Save Changes';$('cancelEdit').classList.remove('hidden');total();window.scrollTo({top:0,behavior:'smooth'})}
async function deleteExpense(id){let confirmation={reason:'Deleted from Payment list'};if(window.belmConfirmDelete){confirmation=await window.belmConfirmDelete({title:'Delete this payment?',message:'The expense/payment record will move to Recycle Bin.'});if(!confirmation)return}else if(!confirm('Delete this payment?'))return;try{await api('/company-expenses/'+encodeURIComponent(id),{method:'DELETE',body:JSON.stringify(confirmation)});show('Payment deleted and moved to Recycle Bin.');await load()}catch(e){show(e.message,true)}}
async function save(e){e.preventDefault();const id=$('expenseId').value;let editConfirmation={};if(id&&window.belmConfirmEdit){const c=await window.belmConfirmEdit({title:'Save payment changes?',message:'Confirm changes to this expense/payment record.'});if(!c)return;editConfirmation=c}const read=await readReceipt($('receiptFile').files[0]).catch(err=>{show(err.message,true);return false});if(read===false)return;const amount=total();$('saveButton').disabled=true;try{await api(id?'/company-expenses/'+encodeURIComponent(id):'/company-expenses',{method:id?'PUT':'POST',body:JSON.stringify({date:$('date').value,category:$('category').value,description:$('description').value.trim(),quantity:Number($('quantity').value||1),unitPrice:Number($('unitPrice').value||0),amount,paymentMethod:$('paymentMethod').value,receiptUrl:$('receiptUrl').value||null,receiptPhoto:read?.dataUrl||null,receiptName:read?.name||null,...editConfirmation})});show(id?'Payment updated successfully.':'Expense saved. It is now visible in Payment list.');await load();resetForm()}catch(err){show(err.message,true)}finally{$('saveButton').disabled=false}}
async function load(){try{const d=await api('/company-expenses');expenses=Array.isArray(d)?d:[];render()}catch(e){show(e.message,true);$('rows').innerHTML='<tr><td colspan="8" class="empty">Could not load payments.</td></tr>'}}
$('quantity').addEventListener('input',total);$('unitPrice').addEventListener('input',total);$('expenseForm').addEventListener('submit',save);$('cancelEdit').onclick=resetForm;$('refreshButton').onclick=load;$('search').addEventListener('input',render);$('filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;activeFilter=b.dataset.filter;$('filters').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render()});load();resetForm();
})();