<?php
header('Cache-Control: no-store, no-cache, must-revalidate');
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Assigned Customer Machines — BELM Technician</title>
  <link rel="stylesheet" href="assets/css/belm-technician-dashboard.css">
  <link rel="stylesheet" href="assets/css/belm-technician-assigned-scope.css?v=8">
  <style>
    @keyframes belmJobCardAlertBlink{
      0%,100%{background:rgba(255,255,255,.07);box-shadow:0 0 0 rgba(255,193,7,0);filter:brightness(1)}
      50%{background:linear-gradient(135deg,#f6c51e,#ff9f1a);color:#14243a;box-shadow:0 0 0 2px rgba(255,255,255,.18),0 0 24px rgba(246,197,30,.85);filter:brightness(1.15)}
    }
    .belm-nav__item.job-card-alert-blink{animation:belmJobCardAlertBlink 1s ease-in-out infinite;border:1px solid rgba(246,197,30,.85)}
    .belm-nav__item.job-card-alert-blink span{font-weight:950}
    .technician-customer-card{min-height:0!important}
    .technician-customer-feed{flex:0 0 auto!important;min-height:0!important;margin-top:12px!important;margin-bottom:12px!important;padding:14px!important}
    .technician-customer-feed-head{margin-bottom:10px!important}
    .technician-customer-feed-body{display:block!important;min-height:0!important;overflow:hidden!important}
    .technician-customer-feed-row{min-height:118px;max-height:145px;overflow:hidden;padding:12px 13px!important}
    .technician-customer-feed-row p{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:4;overflow:hidden;margin:6px 0!important;line-height:1.35!important}
    .technician-customer-feed-row small{display:block;margin-top:4px}
    .machine-board{margin:10px auto 0;width:min(1120px,100%)}
    .machine-board-head{display:flex;align-items:end;justify-content:space-between;gap:16px;margin-bottom:14px;padding:14px 16px;border:1px solid rgba(82,157,217,.35);border-radius:14px;background:#071d34}
    .machine-board-head small{display:block;color:#58d99c;font-size:9px;font-weight:950;letter-spacing:.08em}.machine-board-head h2{margin:4px 0 2px;color:#fff;font-size:22px}.machine-board-head p{margin:0;color:#8faac3;font-size:11px}.machine-board-back{border:1px solid #2b87ca;border-radius:9px;background:#0b4d80;color:#fff;padding:10px 13px;font-weight:900;cursor:pointer}
    .assigned-machine-grid{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:14px!important}.assigned-machine-card{margin:0!important;min-width:0!important}.machine-actions{grid-template-columns:repeat(3,minmax(0,1fr))!important}.machine-actions button{width:100%;border:1px solid #2e7ebc;border-radius:8px;background:#0c67a3;color:#fff;font:800 11px Inter,Arial,sans-serif;cursor:pointer}.machine-actions .reports-button{background:#111f39;border-color:#46a8ea}
    #techMachineReportsDialog{width:min(1040px,95vw);max-height:90vh;padding:0;border:1px solid #355a7d;border-radius:18px;background:#081728;color:#eef6ff;box-shadow:0 28px 80px rgba(0,0,0,.58)}#techMachineReportsDialog::backdrop{background:rgba(1,8,18,.78);backdrop-filter:blur(4px)}.tmr-head{display:flex;justify-content:space-between;gap:16px;padding:20px 22px;border-bottom:1px solid #274563;background:linear-gradient(135deg,#123a65,#0a2038)}.tmr-head small{color:#68e394;font-weight:900;letter-spacing:.08em}.tmr-head h2{margin:4px 0}.tmr-head p{margin:0;color:#9fb5ca;font-size:12px}.tmr-close{border:0;background:transparent;color:#fff;font-size:28px;cursor:pointer}.tmr-body{padding:18px;overflow:auto}.tmr-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.tmr-card{padding:16px;border:1px solid #315170;border-radius:14px;background:linear-gradient(180deg,#10243b,#091727)}.tmr-card h3{margin:0;color:#fff;font-size:17px}.tmr-card p{margin:6px 0 14px;color:#91a9c0;font-size:11px}.tmr-period{display:grid;grid-template-columns:1fr 1fr;gap:9px}.tmr-period label{display:grid;gap:5px;color:#9fb4c8;font-size:9px;font-weight:900;text-transform:uppercase}.tmr-period input{width:100%;padding:9px;border:1px solid #3b5d7a;border-radius:8px;background:#06111f;color:#fff;color-scheme:dark}.tmr-actions{display:grid;grid-template-columns:1fr 1.15fr 1.15fr;gap:8px;margin-top:12px}.tmr-actions button{min-height:38px;border-radius:8px;border:1px solid #3a5f7f;color:#fff;font-weight:900;font-size:10px;cursor:pointer}.tmr-view{background:#1976d2}.tmr-pdf{background:#0f8b4c}.tmr-csv{background:#c99b00;color:#101820!important}.tmr-actions button:disabled{opacity:.35;cursor:not-allowed}.tmr-note{margin-top:8px!important;font-size:9px!important;color:#7f9bb6!important}
    @media(max-width:760px){.assigned-machine-grid,.tmr-grid{grid-template-columns:1fr!important}.machine-board-head{align-items:stretch;flex-direction:column}.machine-actions{grid-template-columns:1fr!important}.tmr-actions{grid-template-columns:1fr}.tmr-period{grid-template-columns:1fr 1fr}}
    @media(prefers-reduced-motion:reduce){.belm-nav__item.job-card-alert-blink{animation:none;background:#f6c51e;color:#14243a;box-shadow:0 0 0 2px rgba(246,197,30,.3)}}
  </style>
</head>
<body class="belm-admin belm-assigned-page" data-assigned-page="machines">
<div class="belm-shell" id="belmShell">
  <aside class="belm-sidebar">
    <div class="belm-brand"><div class="belm-brand__name">BELM<span class="belm-brand__slash">/</span></div><div class="belm-brand__tag">OPERATIONS PLATFORM</div></div>
    <nav class="belm-nav">
      <a href="index.html" class="belm-nav__item" data-nav="home">⌂ <span>Home</span></a>
      <a href="my-job-cards.php" class="belm-nav__item" id="myJobCardsNav">▤ <span>My Job Cards</span></a>
      <a href="customer-machines.php" class="belm-nav__item is-active" data-nav="machines">🚜 <span>Customer Machines</span></a>
      <a href="diagnosis-repair.php" class="belm-nav__item">🔧 <span>Diagnosis Report</span></a>
      <a href="spare-requests.php" class="belm-nav__item">⬡ <span>Spare Requests</span></a>
      <a href="testing-completion.php" class="belm-nav__item">✓ <span>Testing &amp; Completion</span></a>
      <a href="daily-checklists.php" class="belm-nav__item" data-nav="daily">☑ <span>Daily Checklists</span></a>
      <a href="communication.php" class="belm-nav__item">✉ <span>Communication</span></a>
      <a href="my-reports.php" class="belm-nav__item">▥ <span>My Reports</span></a>
      <a href="my-profile.php" class="belm-nav__item">♙ <span>My Profile</span></a>
    </nav>
    <div class="belm-nav__divider"></div>
    <div class="belm-sidebar__foot"><a href="logout.php" class="belm-nav__item">↪ <span>Log out</span></a></div>
  </aside>

  <div class="belm-main">
    <header class="belm-topbar"><div class="belm-topbar__left"><button class="belm-topbar__menu" id="sidebarToggle" type="button">☰</button><span class="belm-topbar__kicker">ASSIGNED CUSTOMER SCOPE</span></div><div class="belm-user"><div><div class="belm-user__name">TECHNICIAN</div><div class="belm-user__role">TECHNICAL DEPARTMENT</div></div></div></header>
    <main class="belm-content">
      <section class="assigned-page-head"><div><small>TECHNICIAN · CUSTOMER ASSIGNMENT</small><h1>My Assigned Customer</h1><p>The approved customer card is shown exactly for the company assigned to this technician. Access switches are view-only here.</p></div><span class="scope-pill">LIVE ASSIGNMENT</span></section>
      <div id="assignedCustomerRoot" class="assigned-loading">Loading assigned customer…</div>
    </main>
  </div>
</div>
<dialog id="techMachineReportsDialog"></dialog>
<script>
(function(){
  'use strict';
  const token=localStorage.getItem('belm_tech_token')||'';
  const root=document.getElementById('assignedCustomerRoot');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const val=(o,...keys)=>{for(const k of keys)if(o&&o[k]!=null&&o[k]!=='')return o[k];return''};
  const bool=v=>v===true||v===1||v==='1'||String(v||'').toLowerCase()==='true';
  const status=m=>{const s=String(val(m,'status','machineStatus','machine_status')||'UNKNOWN').toUpperCase();if(s.includes('RED')||s.includes('CRITICAL'))return['red','RED'];if(s.includes('YELLOW')||s.includes('ATTENTION')||s.includes('WARNING'))return['yellow','ATTENTION'];if(s.includes('GREEN')||s.includes('NORMAL')||s.includes('OK'))return['green','NORMAL'];return['neutral','NOT CHECKED']};
  const fmt=v=>{if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('en-GB',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})};
  async function api(url){const r=await fetch(url,{cache:'no-store',headers:{Authorization:'Bearer '+token}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not load assigned customer.');return d}
  function uniqueMachines(rows){const seen=new Set();return (Array.isArray(rows)?rows:[]).filter(m=>{const key=String(val(m,'id')||val(m,'serialNumber','serial_number')||val(m,'fleetNumber','fleet_number')||val(m,'regNumber','reg_number')||'').trim().toLowerCase();if(!key||seen.has(key))return false;seen.add(key);return true})}
  function machineLabel(m){return val(m,'label')||[val(m,'brand'),val(m,'model')].filter(Boolean).join(' ')||val(m,'machineType','machine_type')||'Machine'}
  function machineCard(m){const s=status(m),id=val(m,'id'),label=machineLabel(m),fleet=val(m,'fleetNumber','fleet_number')||'—',serial=val(m,'serialNumber','serial_number')||'—',reg=val(m,'regNumber','reg_number')||'—';return `<article class="assigned-machine-card status-${s[0]}"><div class="machine-card-top"><div><small>ASSIGNED CUSTOMER MACHINE</small><h3>${esc(label)}</h3><p>Fleet ${esc(fleet)}</p></div><span class="machine-status-pill">${esc(s[1])}</span></div><div class="machine-card-info"><div><span>Fleet No.</span><b>${esc(fleet)}</b></div><div><span>Serial No.</span><b>${esc(serial)}</b></div><div><span>Registration</span><b>${esc(reg)}</b></div></div><div class="machine-actions"><a class="primary" href="daily-checklists.php?machine=${encodeURIComponent(id)}">Check Up</a><a href="/technician-job-cards/?machine=${encodeURIComponent(id)}">Job Card</a><button type="button" class="reports-button" data-machine-reports="${esc(id)}">Reports</button></div></article>`}
  function readonlyToggle(label,on,stateOn,stateOff){return `<div class="tech-readonly-toggle ${on?'on':'off'}"><span class="toggle-label">${esc(label)}</span><span class="tech-toggle-track" aria-hidden="true"></span><span class="toggle-state">${esc(on?stateOn:stateOff)}</span></div>`}
  const communicationSlots=[{key:'service',title:'Service Reminder',empty:'No new service reminder.',match:/service reminder|service due|maintenance due|service overdue|next service|scheduled service/i},{key:'operator',title:'Operator Report',empty:'No new operator report.',match:/operator report|operator|operation report|daily check|daily checklist/i},{key:'job',title:'Job Card Alert',empty:'No new job card alert.',match:/job card|jobcard|technician dispatch|assigned job|diagnosis report|waiting for spare|testing|completed/i}];
  const communicationText=item=>[item?.subject,item?.title,item?.message,item?.body,item?.description,item?.type,item?.category].filter(Boolean).join(' ');const randomItem=items=>items[Math.floor(Math.random()*items.length)];
  function communicationCard(slot,items){const matches=(Array.isArray(items)?items:[]).filter(item=>slot.match.test(communicationText(item)));const item=matches.length?randomItem(matches):null;if(!item)return `<article class="technician-customer-feed-row is-placeholder feed-${slot.key}"><b>${esc(slot.title)}</b><p>${esc(slot.empty)}</p><small>Standing alert slot</small></article>`;return `<article class="technician-customer-feed-row feed-${slot.key}"><b>${esc(slot.title)}</b><p>${esc(item.message||item.body||item.description||item.subject||item.title||'New message available.')}</p><small>${esc(fmt(item.createdAt||item.created_at||item.updatedAt||item.updated_at))}</small></article>`}
  let communicationOrder=[],communicationIndex=0;function nextCommunicationSlot(){if(communicationIndex>=communicationOrder.length){communicationOrder=[...communicationSlots];for(let i=communicationOrder.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[communicationOrder[i],communicationOrder[j]]=[communicationOrder[j],communicationOrder[i]]}communicationIndex=0}return communicationOrder[communicationIndex++]}
  function startCommunicationRotation(items){const body=document.getElementById('communicationFeedBody');if(!body)return;const render=()=>{body.innerHTML=communicationCard(nextCommunicationSlot(),items)};render();window.setInterval(render,9000)}
  function jobNeedsAttention(job){const s=String(job?.status||'').toUpperCase();const stage=String(job?.current_stage||job?.currentStage||'').toUpperCase();if(['COMPLETED','CANCELLED'].includes(s)||stage==='COMPLETED')return false;const explicitNew=['ASSIGNED','OPEN','OPENED','NEW','DISPATCHED','PENDING_RECEIVE'].includes(s)||['ASSIGNED','OPENED','DISPATCHED','PENDING_RECEIVE'].includes(stage);if(explicitNew)return true;const started=Boolean(job?.started_at||job?.startedAt);const hasProgress=Boolean(String(job?.diagnosis||'').trim()||String(job?.work_done||job?.workDone||'').trim()||String(job?.test_result||job?.testResult||'').trim());return !started&&!hasProgress&&s!=='RECEIVED'&&stage!=='RECEIVED'}
  async function syncJobCardAlert(){const nav=document.getElementById('myJobCardsNav');if(!nav||!token)return;try{const jobs=await api('/api/breakdown-workflow/technician-jobs');const count=Array.isArray(jobs)?jobs.filter(jobNeedsAttention).length:0;nav.classList.toggle('job-card-alert-blink',count>0)}catch(_){nav.classList.remove('job-card-alert-blink')}}
  function startJobCardAlertWatch(){syncJobCardAlert();window.setInterval(syncJobCardAlert,15000)}
  const reportCategories=[['checklists','Checklist Report','Daily, inspection and check-up records'],['operator','Operator Report','Operator messages and condition records'],['fuel','Fuel Report','Fuel quantity, cost and consumption'],['job-cards','Job Card Report','Assigned, active and completed Job Cards'],['maintenance','Maintenance Report','Service and maintenance history']];
  function periodParams(card,category,machineId,requireDates){const from=card.querySelector('[data-from]').value||'',to=card.querySelector('[data-to]').value||'';if(requireDates&&(!from||!to))throw new Error('Select both From and To dates first.');if(from&&to&&from>to)throw new Error('From date cannot be after To date.');const p=new URLSearchParams({category,machineId:String(machineId)});if(from)p.set('from',from);if(to)p.set('to',to);return p}
  async function downloadReport(url,name,button){const old=button.textContent;button.disabled=true;button.textContent='Preparing...';try{const r=await fetch(url,{cache:'no-store',headers:{Authorization:'Bearer '+token}});if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(e.error||`Download failed (${r.status})`)}const blob=await r.blob(),href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(href),60000)}finally{button.disabled=false;button.textContent=old}}
  function openReports(machine){const dialog=document.getElementById('techMachineReportsDialog'),id=val(machine,'id'),label=machineLabel(machine),fleet=val(machine,'fleetNumber','fleet_number')||'—';dialog.innerHTML=`<div class="tmr-head"><div><small>MACHINE GENERAL REPORT</small><h2>${esc(label)}</h2><p>Fleet ${esc(fleet)} · Select report type and date range.</p></div><button class="tmr-close" type="button">×</button></div><div class="tmr-body"><div class="tmr-grid">${reportCategories.map(([key,title,note])=>`<article class="tmr-card" data-category="${key}"><h3>${esc(title)}</h3><p>${esc(note)}</p><div class="tmr-period"><label>From<input type="date" data-from></label><label>To<input type="date" data-to></label></div><div class="tmr-actions"><button type="button" class="tmr-view" data-view>VIEW</button><button type="button" class="tmr-pdf" data-pdf disabled>DOWNLOAD PDF</button><button type="button" class="tmr-csv" data-csv disabled>DOWNLOAD CSV</button></div><p class="tmr-note">Choose both dates to enable PDF/CSV.</p></article>`).join('')}</div></div>`;dialog.querySelector('.tmr-close').onclick=()=>dialog.close();dialog.querySelectorAll('.tmr-card').forEach(card=>{const category=card.dataset.category,from=card.querySelector('[data-from]'),to=card.querySelector('[data-to]'),pdf=card.querySelector('[data-pdf]'),csv=card.querySelector('[data-csv]'),note=card.querySelector('.tmr-note');const sync=()=>{const ready=Boolean(from.value&&to.value);pdf.disabled=!ready;csv.disabled=!ready;note.textContent=ready?'Date range selected — download is ready.':'Choose both dates to enable PDF/CSV.'};from.addEventListener('change',sync);to.addEventListener('change',sync);card.querySelector('[data-view]').onclick=()=>{try{location.href=`/tech-report/?${periodParams(card,category,id,false).toString()}`}catch(e){alert(e.message)}};pdf.onclick=e=>{try{const p=periodParams(card,category,id,true);downloadReport(`/api/checklist-reports/technician-general/pdf?${p}`,`BELM-${label}-${category}-${from.value}-to-${to.value}.pdf`,e.currentTarget).catch(x=>alert(x.message))}catch(x){alert(x.message)}};csv.onclick=e=>{try{const p=periodParams(card,category,id,true);downloadReport(`/api/checklist-reports/technician-general/csv?${p}`,`BELM-${label}-${category}-${from.value}-to-${to.value}.csv`,e.currentTarget).catch(x=>alert(x.message))}catch(x){alert(x.message)}};sync()});if(!dialog.open)dialog.showModal()}
  function bindMachineBoard(machines,customer){const view=document.getElementById('viewAssignedMachines'),panel=document.getElementById('customerMachinePanel'),card=document.querySelector('.technician-customer-card');if(!view||!panel||!card)return;view.addEventListener('click',e=>{e.preventDefault();card.hidden=true;panel.hidden=false;panel.scrollIntoView({behavior:'smooth',block:'start'})});panel.addEventListener('click',e=>{const back=e.target.closest('[data-back-customer]');if(back){e.preventDefault();panel.hidden=true;card.hidden=false;card.scrollIntoView({behavior:'smooth',block:'start'});return}const reports=e.target.closest('[data-machine-reports]');if(reports){const machine=machines.find(m=>String(val(m,'id'))===String(reports.getAttribute('data-machine-reports')));if(machine)openReports(machine)}})}
  async function load(){if(!token){location.replace('/login');return}try{const report=await api('/api/checklist-reports/technician-general');let customer=report.customer&&report.customer.id?report.customer:{id:'',name:'Assigned Customer'},machines=uniqueMachines(report.machines);let comm=[];try{comm=await api('/api/customers/'+encodeURIComponent(customer.id)+'/communications')}catch(_){}const active=Number(val(customer,'isActive','is_active')||1)===1,belmProvider=bool(val(customer,'belmServiceProviderActive','belm_service_provider_active'))||!bool(val(customer,'isMachineryAdmin','is_machinery_admin'));root.className='';root.innerHTML=`<section class="technician-customer-card"><div class="technician-customer-head"><div class="technician-customer-title"><p class="technician-customer-eyebrow">Customer</p><h2>${esc(customer.name)}</h2><div class="technician-customer-contact"><div><span>Phone</span><b>${esc(val(customer,'phone','contact')||'Not recorded')}</b></div><div><span>Email</span><b>${esc(val(customer,'email')||'Not recorded')}</b></div><div><span>Address</span><b>${esc(val(customer,'address')||'Not recorded')}</b></div></div></div><div class="technician-customer-controls"><span class="technician-customer-badge ${active?'':'off'}">${active?'Active':'Inactive'}</span>${readonlyToggle(customer.name,belmProvider,'BELM ON','CUSTOMER ON')}${readonlyToggle('Non-payment',active,'PORTAL ON','PORTAL OFF')}</div></div><section class="technician-customer-feed"><div class="technician-customer-feed-head"><strong>Communication<br>history</strong><a href="communication.php">View all</a></div><div class="technician-customer-feed-body" id="communicationFeedBody" aria-live="polite"></div></section><div class="technician-customer-note">Customer management switches are read-only for Technician.</div><nav class="technician-customer-actions"><a href="#customerMachinePanel" id="viewAssignedMachines">View Machine${machines.length>1?` (${machines.length})`:''}</a></nav></section><section id="customerMachinePanel" class="machine-board" hidden><div class="machine-board-head"><div><small>ASSIGNED CUSTOMER MACHINES</small><h2>${esc(customer.name)} Machines</h2><p>Only unique machines assigned under this customer are shown.</p></div><button type="button" class="machine-board-back" data-back-customer>← Back to Customer</button></div><div class="assigned-machine-grid">${machines.length?machines.map(machineCard).join(''):'<div class="assigned-empty">No registered machines found for this assigned customer.</div>'}</div></section>`;bindMachineBoard(machines,customer);startCommunicationRotation(comm);startJobCardAlertWatch()}catch(e){root.className='assigned-error';root.textContent=e.message}}
  document.getElementById('sidebarToggle')?.addEventListener('click',()=>document.getElementById('belmShell')?.classList.toggle('is-sidebar-open'));load();
})();
</script>
</body>
</html>