(()=>{
  const token=localStorage.getItem('belm_customer_token');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function api(p){const r=await fetch(`/api/customer-portal${p}`,{headers:{Authorization:`Bearer ${token||''}`},cache:'no-store'});const d=await r.json().catch(()=>[]);if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
  function rows(items){return items.length?items.map(x=>{const id=x.id||'';const no=x.invoiceNo||x.invoice_no||x.number||'Invoice';const status=x.status||x.customerStatus||'ISSUED';const date=x.date||x.createdAt||x.created_at||'';const total=Number(x.total||0);const balance=Number(x.balance??total);const download=`/api/customer-portal/invoices/${encodeURIComponent(id)}/download`;return `<div class="cb-row"><div><strong>${esc(no)}</strong><small>${esc(status)}${date?` · ${esc(date)}`:''}${Number.isFinite(total)?` · TZS ${total.toLocaleString()}`:''}${Number.isFinite(balance)?` · Balance TZS ${balance.toLocaleString()}`:''}</small></div><div class="cb-actions"><a href="${download}" data-auth-download="${esc(download)}">Download PDF</a></div></div>`}).join(''):'<p>No BELM invoices issued yet.</p>'}
  async function load(){if(!token){location.href='/login';return}try{const [dash,inv]=await Promise.all([api('/dashboard'),api('/invoices')]);document.getElementById('companyName').textContent=dash?.customer?.name||'Customer';const invoices=Array.isArray(inv)?inv:(inv?.items||[]);document.getElementById('invoiceCount').textContent=invoices.length;document.getElementById('invoiceList').innerHTML=rows(invoices);wireDownloads()}catch(e){const a=document.getElementById('alert');a.textContent=e.message;a.hidden=false}}
  function wireDownloads(){document.querySelectorAll('[data-auth-download]').forEach(a=>a.addEventListener('click',async e=>{e.preventDefault();const r=await fetch(a.dataset.authDownload,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok){alert('Could not download invoice.');return}const b=await r.blob(),u=URL.createObjectURL(b),l=document.createElement('a');l.href=u;l.download='BELM-invoice.pdf';document.body.appendChild(l);l.click();l.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}))}
  document.getElementById('refreshButton').addEventListener('click',load);load();
})();
