(function(){
'use strict';
const token=localStorage.getItem('belm_admin_token')||'';
if(!token){location.replace('/login');return;}
let customers=[],proformas=[],inventoryParts=[],page=1;const pageSize=10;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=v=>'TZS '+Number(v||0).toLocaleString('en-TZ',{maximumFractionDigits:2});
const today=()=>{const n=new Date();const l=new Date(n.getTime()-n.getTimezoneOffset()*60000);return l.toISOString().slice(0,10)};
function show(msg,error=false){$('pageAlert').textContent=msg;$('pageAlert').className='page-alert'+(error?' error':'')}
async function api(path,options={}){const r=await fetch('/api'+path,{...options,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token,...(options.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch(_){}if(!r.ok)throw new Error(d?.error||'Request failed');return d}
function customerOptions(selected=''){return '<option value="">Select customer…</option>'+customers.map(c=>`<option value="${esc(c.id)}" ${String(c.id)===String(selected)?'selected':''}>${esc(c.name)}</option>`).join('')}
function fillCustomer(){const c=customers.find(x=>String(x.id)===String($('proformaCustomer').value));$('customerInfo').innerHTML=c?`<strong>${esc(c.name)}</strong><br>${esc(c.address||'')} ${c.phone?'· '+esc(c.phone):''} ${c.email?'· '+esc(c.email):''}`:'Choose a customer.';$('proformaMachine').innerHTML='<option value="">No machine / general</option>'+(c?.machines||[]).map(m=>`<option value="${esc(m.id)}">${esc([m.model,m.regNumber||m.serialNumber].filter(Boolean).join(' · '))}</option>`).join('')}
function inventoryText(part){return [part.partNumber||part.part_number,part.name,part.referenceNumber||part.reference_number].filter(Boolean).join(' · ')}
function inventoryMatches(part,query){if(!query)return true;const q=String(query).trim().toLowerCase();return [part.partNumber,part.part_number,part.referenceNumber,part.reference_number,part.name,part.category,part.machineBrand,part.machineType].some(v=>String(v||'').toLowerCase().includes(q))}
function inventoryOptions(query='',selectedId=''){const filtered=inventoryParts.filter(p=>inventoryMatches(p,query));return '<option value="">Select inventory item…</option>'+filtered.map(p=>{const id=String(p.id||'');const stock=Number(p.stockQty??p.stock_qty??0);return `<option value="${esc(id)}" ${id===String(selectedId)?'selected':''}>${esc(inventoryText(p)||'Inventory item')} · Stock ${esc(stock)}</option>`}).join('')}
function inventoryByPartNumber(value){const needle=String(value||'').trim().toLowerCase();if(!needle)return null;return inventoryParts.find(p=>String(p.partNumber||p.part_number||'').trim().toLowerCase()===needle)||null}
function setInventoryHint(row,part){const hint=row.querySelector('[data-inventory-hint]');if(!hint)return;if(!part){hint.textContent=inventoryParts.length?'Choose an inventory item to auto-fill this line.':'No BELM inventory records available.';hint.className='inventory-hint';return}const stock=Number(part.stockQty??part.stock_qty??0);const selling=Number(part.sellingPrice??part.selling_price??0);const reference=part.referenceNumber||part.reference_number||'No reference';hint.textContent=`Stock ${stock} · ${reference} · Selling ${money(selling)}`;hint.className='inventory-hint '+(stock<=0?'out':stock<=5?'low':'ok')}
function applyInventoryPart(row,part){if(!part){setInventoryHint(row,null);return}row.querySelector('[data-field="partNumber"]').value=part.partNumber||part.part_number||'';row.querySelector('[data-field="description"]').value=part.name||'';row.querySelector('[data-field="unit"]').value='PC';row.querySelector('[data-field="unitPrice"]').value=Number(part.sellingPrice??part.selling_price??0);const search=row.querySelector('[data-inventory-search]');if(search)search.value=inventoryText(part);setInventoryHint(row,part)}
function bindInventoryPicker(row,item={}){const search=row.querySelector('[data-inventory-search]');const select=row.querySelector('[data-inventory-select]');let matched=inventoryParts.find(p=>String(p.id||'')===String(item.inventoryPartId||item.inventory_part_id||''))||inventoryByPartNumber(item.partNumber||item.part_number);const selectedId=matched?.id||'';select.innerHTML=inventoryOptions('',selectedId);if(matched){select.value=String(matched.id);search.value=inventoryText(matched);setInventoryHint(row,matched)}else setInventoryHint(row,null);
search.addEventListener('input',()=>{const keep=select.value;select.innerHTML=inventoryOptions(search.value,keep);if(keep&&[...select.options].some(o=>o.value===keep))select.value=keep;else select.value='';setInventoryHint(row,select.value?inventoryParts.find(p=>String(p.id)===String(select.value)):null)});
search.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const options=[...select.options].filter(o=>o.value);if(options.length===1){e.preventDefault();select.value=options[0].value;select.dispatchEvent(new Event('change'))}});
select.addEventListener('change',()=>{const part=inventoryParts.find(p=>String(p.id)===String(select.value));if(part)applyInventoryPart(row,part);else setInventoryHint(row,null)});
row.querySelector('[data-field="partNumber"]').addEventListener('change',e=>{const part=inventoryByPartNumber(e.target.value);if(part){select.innerHTML=inventoryOptions('',part.id);select.value=String(part.id);search.value=inventoryText(part);setInventoryHint(row,part)}})}
function itemRow(item={}){const row=document.createElement('div');row.className='item-row';row.innerHTML=`<div class="inventory-picker"><label>Search inventory<input type="search" data-inventory-search placeholder="Part no., name, reference…" autocomplete="off"></label><label>Select from inventory<select data-inventory-select><option value="">Loading inventory…</option></select></label><small data-inventory-hint class="inventory-hint">Loading BELM inventory…</small></div><label>Part No.<input data-field="partNumber" value="${esc(item.partNumber||item.part_number||'')}"></label><label>Description<input data-field="description" required value="${esc(item.description||'')}"></label><label>Qty<input data-field="qty" type="number" min="1" step="1" required value="${esc(item.qty||item.quantity||1)}"></label><label>Unit<input data-field="unit" value="${esc(item.unit||'PC')}"></label><label>Unit Price<input data-field="unitPrice" type="number" min="0" step="0.01" required value="${esc(item.unitPrice||item.unit_price||0)}"></label><button type="button" class="remove-item">×</button>`;row.querySelector('.remove-item').onclick=()=>{if($('proformaItems').children.length>1)row.remove()};bindInventoryPicker(row,item);return row}
function resetForm(){ $('proformaForm').reset();$('proformaId').value='';$('proformaSourceJobCardId').value='';$('proformaSourceSpareRequestId').value='';$('proformaSourceSpareRequestIds').value='';$('formTitle').textContent='New Proforma';$('editBadge').classList.add('hidden');$('cancelEditButton').classList.add('hidden');$('saveProformaButton').textContent='Save Proforma';$('proformaCustomer').disabled=false;$('proformaDate').disabled=false;$('proformaCustomer').innerHTML=customerOptions();$('proformaMachine').innerHTML='<option value="">No machine / general</option>';$('customerInfo').textContent='Choose a customer.';$('proformaDate').value=today();$('proformaVatMode').value='VAT';$('proformaVatRate').value='18';$('proformaDiscountType').value='FIXED';$('proformaDiscount').value='0';$('proformaItems').replaceChildren(itemRow({}));}
function editProforma(id){const p=proformas.find(x=>String(x.id)===String(id));if(!p)return;$('proformaId').value=p.id;$('proformaSourceJobCardId').value=p.sourceJobCardId||p.source_job_card_id||'';$('proformaSourceSpareRequestId').value=p.sourceSpareRequestId||p.source_spare_request_id||'';$('proformaSourceSpareRequestIds').value=(p.sourceSpareRequestIds||[]).join(',');$('formTitle').textContent='Edit '+(p.invoiceNo||'Proforma');$('editBadge').classList.remove('hidden');$('cancelEditButton').classList.remove('hidden');$('saveProformaButton').textContent='Save Changes';$('proformaCustomer').innerHTML=customerOptions(p.customer?.id||p.customerId||'');fillCustomer();$('proformaMachine').value=p.machineId||'';$('proformaDate').value=p.date||today();$('proformaVatMode').value=p.vatMode||'VAT';$('proformaVatRate').value=p.vatRate??18;$('proformaDiscountType').value=p.discountType||'FIXED';$('proformaDiscount').value=p.discount||0;$('proformaPaymentTerms').value=p.paymentTerms||'';$('proformaDeliveryTime').value=p.deliveryTime||'';$('proformaQuoteValidity').value=p.quoteValidity||'';$('proformaNotice').value=p.notice||'';$('proformaItems').replaceChildren(...((p.items?.length?p.items:[{}]).map(itemRow)));$('proformaCustomer').disabled=true;$('proformaDate').disabled=true;window.scrollTo({top:0,behavior:'smooth'})}
function render(){const q=$('proformaSearch').value.toLowerCase().trim();const rows=proformas.filter(p=>!q||[p.invoiceNo,p.customer?.name,p.customerResponse,p.deliveryStatus].join(' ').toLowerCase().includes(q));const pages=Math.max(1,Math.ceil(rows.length/pageSize));if(page>pages)page=pages;const start=(page-1)*pageSize,part=rows.slice(start,start+pageSize);$('proformaCount').textContent=rows.length;$('pageLabel').textContent=`Page ${page} of ${pages}`;$('prevPage').disabled=page<=1;$('nextPage').disabled=page>=pages;$('proformaRows').innerHTML=part.length?part.map((p,idx)=>{const generated=Boolean(p.generatedInvoiceId);return `<tr><td>${start+idx+1}</td><td><strong>${esc(p.invoiceNo||'—')}</strong>${generated?`<span class="linked-invoice">→ ${esc(p.generatedInvoiceNo||'Invoice generated')}</span>`:''}</td><td>${esc(p.customer?.name||'—')}</td><td>${esc(p.date||p.createdAt||'—')}</td><td>${money(p.totals?.grandTotal)}</td><td>${esc(p.customerResponse||p.deliveryStatus||'DRAFT')}</td><td><div class="actions"><a class="pdf" href="/api/proforma-invoices?action=export-one&proformaId=${encodeURIComponent(p.id)}&token=${encodeURIComponent(token)}" target="_blank" rel="noopener">PDF</a><button class="edit" data-edit="${esc(p.id)}">Edit</button>${generated?`<a class="generated" href="/invoice-manager/">✓ Invoice ${esc(p.generatedInvoiceNo||'')}</a>`:`<button class="generate" data-generate="${esc(p.id)}">Generate Invoice</button>`}<button class="delete" data-delete="${esc(p.id)}">Delete</button></div></td></tr>`}).join(''):'<tr><td colspan="7" class="empty-row">No Proformas found.</td></tr>';$('proformaRows').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProforma(b.dataset.edit));$('proformaRows').querySelectorAll('[data-generate]').forEach(b=>b.onclick=()=>openGenerateInvoice(b.dataset.generate));$('proformaRows').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteProforma(b.dataset.delete))}
function openGenerateInvoice(id){const p=proformas.find(x=>String(x.id)===String(id));if(!p)return;$('generateProformaId').value=p.id;$('paymentReceived').checked=false;$('paymentFields').classList.add('hidden');$('paymentMethod').value='BANK';$('paymentAmount').value=Number(p.totals?.grandTotal||0).toFixed(2);$('paymentReference').value='';$('generateSummary').innerHTML=`<strong>${esc(p.invoiceNo||'Proforma')} · ${esc(p.customer?.name||'Customer')}</strong><span>Invoice total: ${money(p.totals?.grandTotal||0)}</span><span>If payment has not been received, leave the checkbox off. The Invoice will be UNPAID.</span>`;$('generateInvoiceDialog').showModal()}
function closeGenerateInvoice(){if($('generateInvoiceDialog').open)$('generateInvoiceDialog').close()}
async function submitGenerateInvoice(e){e.preventDefault();const id=$('generateProformaId').value;if(!id)return;const received=$('paymentReceived').checked;const button=$('confirmGenerateButton');button.disabled=true;const old=button.textContent;button.textContent=received?'Generating & Recording Payment…':'Generating Invoice…';try{const result=await api('/proforma-generate-invoice',{method:'POST',body:JSON.stringify({proformaId:id,paymentReceived:received,paymentMethod:received?$('paymentMethod').value:null,paymentAmount:received?Number($('paymentAmount').value||0):null,paymentReference:received?$('paymentReference').value.trim():null})});closeGenerateInvoice();if(result.status==='PAID')show(`Invoice ${result.invoiceNo} generated and full payment recorded. Status: PAID.`);else if(result.status==='PARTIALLY_PAID')show(`Invoice ${result.invoiceNo} generated. Partial payment recorded; remaining balance is still outstanding.`);else show(`Invoice ${result.invoiceNo} generated as UNPAID. Record payment only after money is received.`);await load();setTimeout(()=>{location.href='/invoice-manager/'},650)}catch(err){show(err.message,true)}finally{button.disabled=false;button.textContent=old}}
async function deleteProforma(id){let confirmation={reason:'Deleted from Proforma Manager'};if(window.belmConfirmDelete){confirmation=await window.belmConfirmDelete({title:'Delete this Proforma?',message:'This Proforma will move to the Recycle Bin.'});if(!confirmation)return}else if(!confirm('Delete this Proforma?'))return;try{await api('/proforma-invoices/'+encodeURIComponent(id),{method:'DELETE',body:JSON.stringify(confirmation)});show('Proforma moved to Recycle Bin.');await load()}catch(e){show(e.message,true)}}
async function save(e){e.preventDefault();const id=$('proformaId').value;const items=[...$('proformaItems').querySelectorAll('.item-row')].map(row=>({partNumber:row.querySelector('[data-field="partNumber"]').value.trim(),description:row.querySelector('[data-field="description"]').value.trim(),qty:Number(row.querySelector('[data-field="qty"]').value),unit:row.querySelector('[data-field="unit"]').value.trim()||'PC',unitPrice:Number(row.querySelector('[data-field="unitPrice"]').value)}));$('saveProformaButton').disabled=true;try{const saved=await api(id?'/proforma-invoices/'+encodeURIComponent(id):'/proforma-invoices',{method:id?'PUT':'POST',body:JSON.stringify({customerId:$('proformaCustomer').value,date:$('proformaDate').value,vatMode:$('proformaVatMode').value,vatRate:Number($('proformaVatRate').value||18),discountType:$('proformaDiscountType').value,discount:Number($('proformaDiscount').value||0),paymentTerms:$('proformaPaymentTerms').value.trim(),deliveryTime:$('proformaDeliveryTime').value.trim(),quoteValidity:$('proformaQuoteValidity').value.trim(),notice:$('proformaNotice').value.trim(),machineId:$('proformaMachine').value||'',sourceSpareRequestId:$('proformaSourceSpareRequestId').value||'',sourceSpareRequestIds:$('proformaSourceSpareRequestIds').value.split(',').map(x=>x.trim()).filter(Boolean),sourceJobCardId:$('proformaSourceJobCardId').value||'',items})});show(id?'Proforma updated successfully.':`Proforma ${saved?.invoiceNo||''} saved successfully.`);await load();resetForm()}catch(err){show(err.message,true)}finally{$('saveProformaButton').disabled=false}}
async function load(){try{const inventoryPromise=api('/spare-parts').catch(()=>[]);const [p,c,inv]=await Promise.all([api('/proforma-invoices'),api('/billing?action=customer-lookup'),inventoryPromise]);proformas=Array.isArray(p)?p:[];customers=Array.isArray(c)?c:[];inventoryParts=Array.isArray(inv)?inv:[];render()}catch(e){show(e.message,true);$('proformaRows').innerHTML='<tr><td colspan="7" class="empty-row">Could not load Proformas.</td></tr>'}}
$('proformaCustomer').addEventListener('change',fillCustomer);$('addItemButton').onclick=()=>$('proformaItems').appendChild(itemRow({}));$('newProformaButton').onclick=resetForm;$('cancelEditButton').onclick=resetForm;$('proformaForm').addEventListener('submit',save);$('proformaSearch').addEventListener('input',()=>{page=1;render()});$('prevPage').onclick=()=>{if(page>1){page--;render()}};$('nextPage').onclick=()=>{page++;render()};$('refreshButton').onclick=load;$('logoutButton').onclick=()=>{localStorage.removeItem('belm_admin_token');localStorage.removeItem('belm_admin_user');location.href='/login'};$('paymentReceived').addEventListener('change',()=>{$('paymentFields').classList.toggle('hidden',!$('paymentReceived').checked)});$('closeGenerateDialog').onclick=closeGenerateInvoice;$('cancelGenerateButton').onclick=closeGenerateInvoice;$('generateInvoiceForm').addEventListener('submit',submitGenerateInvoice);load().then(resetForm);
})();