(function(){
'use strict';
const token=localStorage.getItem('belm_admin_token')||'';
if(!token){location.replace('/login');return;}
let customers=[],proformas=[],page=1;const pageSize=10;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=v=>'TZS '+Number(v||0).toLocaleString('en-TZ',{maximumFractionDigits:2});
const today=()=>{const n=new Date();const l=new Date(n.getTime()-n.getTimezoneOffset()*60000);return l.toISOString().slice(0,10)};
function show(msg,error=false){$('pageAlert').textContent=msg;$('pageAlert').className='page-alert'+(error?' error':'')}
async function api(path,options={}){const r=await fetch('/api'+path,{...options,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token,...(options.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch(_){}if(!r.ok)throw new Error(d?.error||'Request failed');return d}
function customerOptions(selected=''){return '<option value="">Select customer…</option>'+customers.map(c=>`<option value="${esc(c.id)}" ${String(c.id)===String(selected)?'selected':''}>${esc(c.name)}</option>`).join('')}
function fillCustomer(){const c=customers.find(x=>String(x.id)===String($('proformaCustomer').value));$('customerInfo').innerHTML=c?`<strong>${esc(c.name)}</strong><br>${esc(c.address||'')} ${c.phone?'· '+esc(c.phone):''} ${c.email?'· '+esc(c.email):''}`:'Choose a customer.';$('proformaMachine').innerHTML='<option value="">No machine / general</option>'+(c?.machines||[]).map(m=>`<option value="${esc(m.id)}">${esc([m.model,m.regNumber||m.serialNumber].filter(Boolean).join(' · '))}</option>`).join('')}
function itemRow(item={}){const row=document.createElement('div');row.className='item-row';row.innerHTML=`<label>Part No.<input data-field="partNumber" value="${esc(item.partNumber||item.part_number||'')}"></label><label>Description<input data-field="description" required value="${esc(item.description||'')}"></label><label>Qty<input data-field="qty" type="number" min="1" step="1" required value="${esc(item.qty||item.quantity||1)}"></label><label>Unit<input data-field="unit" value="${esc(item.unit||'PC')}"></label><label>Unit Price<input data-field="unitPrice" type="number" min="0" step="0.01" required value="${esc(item.unitPrice||item.unit_price||0)}"></label><button type="button" class="remove-item">×</button>`;row.querySelector('.remove-item').onclick=()=>{if($('proformaItems').children.length>1)row.remove()};return row}
function resetForm(){ $('proformaForm').reset();$('proformaId').value='';$('proformaSourceJobCardId').value='';$('proformaSourceSpareRequestId').value='';$('proformaSourceSpareRequestIds').value='';$('formTitle').textContent='New Proforma';$('editBadge').classList.add('hidden');$('cancelEditButton').classList.add('hidden');$('saveProformaButton').textContent='Save Proforma';$('proformaCustomer').disabled=false;$('proformaDate').disabled=false;$('proformaCustomer').innerHTML=customerOptions();$('proformaMachine').innerHTML='<option value="">No machine / general</option>';$('customerInfo').textContent='Choose a customer.';$('proformaDate').value=today();$('proformaVatMode').value='VAT';$('proformaVatRate').value='18';$('proformaDiscountType').value='FIXED';$('proformaDiscount').value='0';$('proformaItems').replaceChildren(itemRow({}));}
function editProforma(id){const p=proformas.find(x=>String(x.id)===String(id));if(!p)return;$('proformaId').value=p.id;$('proformaSourceJobCardId').value=p.sourceJobCardId||p.source_job_card_id||'';$('proformaSourceSpareRequestId').value=p.sourceSpareRequestId||p.source_spare_request_id||'';$('proformaSourceSpareRequestIds').value=(p.sourceSpareRequestIds||[]).join(',');$('formTitle').textContent='Edit '+(p.invoiceNo||'Proforma');$('editBadge').classList.remove('hidden');$('cancelEditButton').classList.remove('hidden');$('saveProformaButton').textContent='Save Changes';$('proformaCustomer').innerHTML=customerOptions(p.customer?.id||p.customerId||'');fillCustomer();$('proformaMachine').value=p.machineId||'';$('proformaDate').value=p.date||today();$('proformaVatMode').value=p.vatMode||'VAT';$('proformaVatRate').value=p.vatRate??18;$('proformaDiscountType').value=p.discountType||'FIXED';$('proformaDiscount').value=p.discount||0;$('proformaPaymentTerms').value=p.paymentTerms||'';$('proformaDeliveryTime').value=p.deliveryTime||'';$('proformaQuoteValidity').value=p.quoteValidity||'';$('proformaNotice').value=p.notice||'';$('proformaItems').replaceChildren(...((p.items?.length?p.items:[{}]).map(itemRow)));$('proformaCustomer').disabled=true;$('proformaDate').disabled=true;window.scrollTo({top:0,behavior:'smooth'})}
function render(){const q=$('proformaSearch').value.toLowerCase().trim();const rows=proformas.filter(p=>!q||[p.invoiceNo,p.customer?.name,p.customerResponse,p.deliveryStatus].join(' ').toLowerCase().includes(q));const pages=Math.max(1,Math.ceil(rows.length/pageSize));if(page>pages)page=pages;const start=(page-1)*pageSize,part=rows.slice(start,start+pageSize);$('proformaCount').textContent=rows.length;$('pageLabel').textContent=`Page ${page} of ${pages}`;$('prevPage').disabled=page<=1;$('nextPage').disabled=page>=pages;$('proformaRows').innerHTML=part.length?part.map((p,idx)=>{const generated=Boolean(p.generatedInvoiceId);return `<tr><td>${start+idx+1}</td><td><strong>${esc(p.invoiceNo||'—')}</strong>${generated?`<span class="linked-invoice">→ ${esc(p.generatedInvoiceNo||'Invoice generated')}</span>`:''}</td><td>${esc(p.customer?.name||'—')}</td><td>${esc(p.date||p.createdAt||'—')}</td><td>${money(p.totals?.grandTotal)}</td><td>${esc(p.customerResponse||p.deliveryStatus||'DRAFT')}</td><td><div class="actions"><a class="pdf" href="/api/proforma-invoices?action=export-one&proformaId=${encodeURIComponent(p.id)}&token=${encodeURIComponent(token)}" target="_blank" rel="noopener">PDF</a><button class="edit" data-edit="${esc(p.id)}">Edit</button>${generated?`<a class="generated" href="/invoice-manager/">✓ Invoice ${esc(p.generatedInvoiceNo||'')}</a>`:`<button class="generate" data-generate="${esc(p.id)}">Generate Invoice</button>`}<button class="delete" data-delete="${esc(p.id)}">Delete</button></div></td></tr>`}).join(''):'<tr><td colspan="7" class="empty-row">No Proformas found.</td></tr>';$('proformaRows').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProforma(b.dataset.edit));$('proformaRows').querySelectorAll('[data-generate]').forEach(b=>b.onclick=()=>generateInvoice(b.dataset.generate,b));$('proformaRows').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteProforma(b.dataset.delete))}
async function generateInvoice(id,button){button.disabled=true;const old=button.textContent;button.textContent='Generating…';try{const result=await api('/billing?action=generate-from-proforma',{method:'POST',body:JSON.stringify({proformaId:id})});show(`Invoice ${result.invoiceNo||''} generated from ${result.proformaNo||'Proforma'} and added to Invoice List.`);await load();setTimeout(()=>{location.href='/invoice-manager/'},500)}catch(e){show(e.message,true)}finally{button.disabled=false;button.textContent=old}}
async function deleteProforma(id){let confirmation={reason:'Deleted from Proforma Manager'};if(window.belmConfirmDelete){confirmation=await window.belmConfirmDelete({title:'Delete this Proforma?',message:'This Proforma will move to the Recycle Bin.'});if(!confirmation)return}else if(!confirm('Delete this Proforma?'))return;try{await api('/proforma-invoices/'+encodeURIComponent(id),{method:'DELETE',body:JSON.stringify(confirmation)});show('Proforma moved to Recycle Bin.');await load()}catch(e){show(e.message,true)}}
async function save(e){e.preventDefault();const id=$('proformaId').value;const items=[...$('proformaItems').querySelectorAll('.item-row')].map(row=>({partNumber:row.querySelector('[data-field="partNumber"]').value.trim(),description:row.querySelector('[data-field="description"]').value.trim(),qty:Number(row.querySelector('[data-field="qty"]').value),unit:row.querySelector('[data-field="unit"]').value.trim()||'PC',unitPrice:Number(row.querySelector('[data-field="unitPrice"]').value)}));$('saveProformaButton').disabled=true;try{const saved=await api(id?'/proforma-invoices/'+encodeURIComponent(id):'/proforma-invoices',{method:id?'PUT':'POST',body:JSON.stringify({customerId:$('proformaCustomer').value,date:$('proformaDate').value,vatMode:$('proformaVatMode').value,vatRate:Number($('proformaVatRate').value||18),discountType:$('proformaDiscountType').value,discount:Number($('proformaDiscount').value||0),paymentTerms:$('proformaPaymentTerms').value.trim(),deliveryTime:$('proformaDeliveryTime').value.trim(),quoteValidity:$('proformaQuoteValidity').value.trim(),notice:$('proformaNotice').value.trim(),machineId:$('proformaMachine').value||'',sourceSpareRequestId:$('proformaSourceSpareRequestId').value||'',sourceSpareRequestIds:$('proformaSourceSpareRequestIds').value.split(',').map(x=>x.trim()).filter(Boolean),sourceJobCardId:$('proformaSourceJobCardId').value||'',items})});show(id?'Proforma updated successfully.':`Proforma ${saved?.invoiceNo||''} saved successfully.`);await load();resetForm()}catch(err){show(err.message,true)}finally{$('saveProformaButton').disabled=false}}
async function load(){try{const [p,c]=await Promise.all([api('/proforma-invoices'),api('/billing?action=customer-lookup')]);proformas=Array.isArray(p)?p:[];customers=Array.isArray(c)?c:[];render()}catch(e){show(e.message,true);$('proformaRows').innerHTML='<tr><td colspan="7" class="empty-row">Could not load Proformas.</td></tr>'}}
$('proformaCustomer').addEventListener('change',fillCustomer);$('addItemButton').onclick=()=>$('proformaItems').appendChild(itemRow({}));$('newProformaButton').onclick=resetForm;$('cancelEditButton').onclick=resetForm;$('proformaForm').addEventListener('submit',save);$('proformaSearch').addEventListener('input',()=>{page=1;render()});$('prevPage').onclick=()=>{if(page>1){page--;render()}};$('nextPage').onclick=()=>{page++;render()};$('refreshButton').onclick=load;$('logoutButton').onclick=()=>{localStorage.removeItem('belm_admin_token');localStorage.removeItem('belm_admin_user');location.href='/login'};load().then(resetForm);
})();