(()=>{
 const token=localStorage.getItem('belm_admin_token');if(!token){location.replace('/login');return}
 let user=null;try{user=JSON.parse(localStorage.getItem('belm_admin_user')||'null')}catch(_){ }const role=String(user?.role||'').toLowerCase();if(role!=='super admin'&&user?.allowedPages!==null){location.replace('/belm-workshop/');return}
 const $=id=>document.getElementById(id), msg=$('message');
 async function api(path,opt={}){const r=await fetch('/api'+path,{...opt,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(opt.headers||{})},cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
 function show(t,error=false){msg.textContent=t;msg.classList.toggle('error',error);msg.hidden=false}
 function setStatus(id,ready,label){const el=$(id);el.textContent=ready?`${label} Connected`:`${label} Not Connected`;el.className=ready?'ok':'off'}
 async function load(){msg.hidden=true;try{const [s,p]=await Promise.all([api('/settings'),api('/notification-config/status')]);$('managementMailEnabled').checked=s.managementMailEnabled!==false;$('managementMailFromName').value=s.managementMailFromName||'BELM Management';$('managementMailReplyTo').value=s.managementMailReplyTo||'';$('managementMailArchiveEnabled').checked=s.managementMailArchiveEnabled!==false;const n=s.notificationConfiguration||{};$('notifyJobCard').checked=n.jobCard!==false;$('notifyMaintenance').checked=n.maintenance!==false;$('notifyProcurement').checked=n.procurement!==false;$('notifyInvoice').checked=n.invoice!==false;$('notifySystem').checked=n.system!==false;$('emailNotificationsEnabled').checked=s.emailNotificationsEnabled!==false;$('whatsappAlertsEnabled').checked=s.whatsappAlertsEnabled!==false;$('whatsappManagementGroup').value=s.whatsappManagementGroup||'';$('smsNotificationsEnabled').checked=s.smsNotificationsEnabled===true;$('smsSenderName').value=s.smsSenderName||'BELM';setStatus('emailStatus',!!p.email,'Email');setStatus('whatsappStatus',!!p.whatsapp,'WhatsApp');setStatus('smsStatus',!!p.sms,'SMS')}catch(e){show(e.message,true)}}
 async function put(key,value){return api(`/settings/${encodeURIComponent(key)}`,{method:'PUT',body:JSON.stringify({value})})}
 $('save').addEventListener('click',async()=>{const b=$('save');b.disabled=true;try{await Promise.all([put('managementMailEnabled',$('managementMailEnabled').checked),put('managementMailFromName',$('managementMailFromName').value.trim()),put('managementMailReplyTo',$('managementMailReplyTo').value.trim()),put('managementMailArchiveEnabled',$('managementMailArchiveEnabled').checked),put('notificationConfiguration',{jobCard:$('notifyJobCard').checked,maintenance:$('notifyMaintenance').checked,procurement:$('notifyProcurement').checked,invoice:$('notifyInvoice').checked,system:$('notifySystem').checked}),put('emailNotificationsEnabled',$('emailNotificationsEnabled').checked),put('whatsappAlertsEnabled',$('whatsappAlertsEnabled').checked),put('whatsappManagementGroup',$('whatsappManagementGroup').value.trim()),put('smsNotificationsEnabled',$('smsNotificationsEnabled').checked),put('smsSenderName',$('smsSenderName').value.trim()||'BELM')]);show('Communication settings saved. Existing messages and notification history were not deleted.')}catch(e){show(e.message,true)}finally{b.disabled=false}});
 $('refresh').addEventListener('click',load);load();
})();
