(()=>{
 const token=localStorage.getItem('belm_admin_token');if(!token){location.replace('/login');return}
 let user=null;try{user=JSON.parse(localStorage.getItem('belm_admin_user')||'null')}catch(_){ }const role=String(user?.role||'').toLowerCase();if(role!=='super admin'&&user?.allowedPages!==null){location.replace('/belm-workshop/');return}
 const $=id=>document.getElementById(id), msg=$('message');
 let managementMailDirectory={companies:[],defaultRoles:[]};let managementMailRouting={};
 async function api(path,opt={}){const r=await fetch('/api'+path,{...opt,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(opt.headers||{})},cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
 function show(t,error=false){msg.textContent=t;msg.classList.toggle('error',error);msg.hidden=false}
 function setStatus(id,ready,label){const el=$(id);el.textContent=ready?`${label} Connected`:`${label} Not Connected`;el.className=ready?'ok':'off'}
 function parseEmails(raw){return [...new Set(String(raw||'').split(/[\n,;]+/).map(v=>v.trim().toLowerCase()).filter(Boolean))]}
 function roleKey(v){return String(v||'').trim().toLowerCase()}
 function companyConfig(id){const current=managementMailRouting[id];return current&&typeof current==='object'?current:{enabled:false,roles:[],groupEmails:[]}}
 function renderManagementMailRecipients(){const id=$('managementMailCompany')?.value||'';const company=managementMailDirectory.companies.find(c=>String(c.id)===String(id));const wrap=$('managementMailRecipientPreview');if(!wrap)return;if(!company){wrap.innerHTML='<div class="empty-note">Select a company to preview recipient emails.</div>';return}const selectedRoles=[...document.querySelectorAll('[data-management-role]:checked')].map(el=>roleKey(el.dataset.managementRole));const cfgEmails=parseEmails($('managementMailGroupEmails')?.value||'');const rows=[];for(const r of company.recipients||[]){if(selectedRoles.includes(roleKey(r.role)))rows.push({email:r.email,label:`${r.name||r.role} · ${r.role}`})}for(const email of cfgEmails)rows.push({email,label:'Group email'});const unique=[...new Map(rows.filter(r=>r.email).map(r=>[r.email.toLowerCase(),r])).values()];wrap.innerHTML=unique.length?unique.map(r=>`<div class="recipient-row"><span>${r.email}</span><small>${r.label}</small></div>`).join(''):'<div class="empty-note">No recipients selected yet. Choose one or more roles or add group email addresses.</div>'}
 function renderManagementMailCompany(){const select=$('managementMailCompany');if(!select)return;const id=select.value;const company=managementMailDirectory.companies.find(c=>String(c.id)===String(id));const cfg=companyConfig(id);const note=$('managementMailCompanyNote');if(note)note.textContent=company?`${company.name} — management email is ${cfg.enabled?'enabled':'disabled'} for this company.`:'Choose a registered company to configure its management email.';const roleWrap=$('managementMailRoles');if(roleWrap){const roles=[...managementMailDirectory.defaultRoles,...(company?.recipients||[]).map(r=>r.role)].filter(Boolean);const unique=[...new Map(roles.map(r=>[roleKey(r),r])).values()];roleWrap.innerHTML=unique.length?unique.map(r=>`<label><input type="checkbox" data-management-role="${String(r).replace(/"/g,'&quot;')}" ${cfg.roles.map(roleKey).includes(roleKey(r))?'checked':''}> ${r}</label>`).join(''):'<div class="empty-note">No company roles found.</div>';}const group=$('managementMailGroupEmails');if(group)group.value=(cfg.groupEmails||[]).join('\n');renderManagementMailRecipients()}
 function bindManagementMail(){const select=$('managementMailCompany');if(!select)return;select.addEventListener('change',renderManagementMailCompany);$('managementMailRoles')?.addEventListener('change',renderManagementMailRecipients);$('managementMailGroupEmails')?.addEventListener('input',renderManagementMailRecipients)}
 async function load(){msg.hidden=true;try{const [s,p,dir]=await Promise.all([api('/settings'),api('/notification-config/status'),api('/settings?action=management-mail-directory')]);$('managementMailEnabled').checked=s.managementMailEnabled!==false;$('managementMailFromName').value=s.managementMailFromName||'BELM Management';$('managementMailReplyTo').value=s.managementMailReplyTo||'';$('managementMailArchiveEnabled').checked=s.managementMailArchiveEnabled!==false;managementMailDirectory=dir||{companies:[],defaultRoles:[]};managementMailRouting=s.managementMailCompanyRouting&&typeof s.managementMailCompanyRouting==='object'?s.managementMailCompanyRouting:{};const companySelect=$('managementMailCompany');if(companySelect){companySelect.innerHTML='<option value="">Select company…</option>'+managementMailDirectory.companies.map(c=>`<option value="${c.id}">${c.name}</option>`).join('');renderManagementMailCompany()}const n=s.notificationConfiguration||{};$('notifyJobCard').checked=n.jobCard!==false;$('notifyMaintenance').checked=n.maintenance!==false;$('notifyProcurement').checked=n.procurement!==false;$('notifyInvoice').checked=n.invoice!==false;$('notifySystem').checked=n.system!==false;$('emailNotificationsEnabled').checked=s.emailNotificationsEnabled!==false;$('whatsappAlertsEnabled').checked=s.whatsappAlertsEnabled!==false;$('whatsappManagementGroup').value=s.whatsappManagementGroup||'';$('smsNotificationsEnabled').checked=s.smsNotificationsEnabled===true;$('smsSenderName').value=s.smsSenderName||'BELM';setStatus('emailStatus',!!p.email,'Email');setStatus('whatsappStatus',!!p.whatsapp,'WhatsApp');setStatus('smsStatus',!!p.sms,'SMS')}catch(e){show(e.message,true)}}
 async function put(key,value){return api(`/settings/${encodeURIComponent(key)}`,{method:'PUT',body:JSON.stringify({value})})}
 $('save').addEventListener('click',async()=>{const b=$('save');b.disabled=true;try{const companyId=$('managementMailCompany')?.value||'';if(companyId){managementMailRouting[companyId]={enabled:true,roles:[...document.querySelectorAll('[data-management-role]:checked')].map(el=>el.dataset.managementRole),groupEmails:parseEmails($('managementMailGroupEmails')?.value||'')}}await Promise.all([put('managementMailEnabled',$('managementMailEnabled').checked),put('managementMailFromName',$('managementMailFromName').value.trim()),put('managementMailReplyTo',$('managementMailReplyTo').value.trim()),put('managementMailArchiveEnabled',$('managementMailArchiveEnabled').checked),put('managementMailCompanyRouting',managementMailRouting),put('notificationConfiguration',{jobCard:$('notifyJobCard').checked,maintenance:$('notifyMaintenance').checked,procurement:$('notifyProcurement').checked,invoice:$('notifyInvoice').checked,system:$('notifySystem').checked}),put('emailNotificationsEnabled',$('emailNotificationsEnabled').checked),put('whatsappAlertsEnabled',$('whatsappAlertsEnabled').checked),put('whatsappManagementGroup',$('whatsappManagementGroup').value.trim()),put('smsNotificationsEnabled',$('smsNotificationsEnabled').checked),put('smsSenderName',$('smsSenderName').value.trim()||'BELM')]);if(companyId)renderManagementMailCompany();show('Communication settings saved. Existing messages and notification history were not deleted.')}catch(e){show(e.message,true)}finally{b.disabled=false}});
 $('refresh').addEventListener('click',load);bindManagementMail();load();
})();
