(function(){
'use strict';
const token=localStorage.getItem('belm_admin_token')||'';
if(!token){location.replace('/login');return}
let customers=[],invoices=[],page=1;const pageSize=10;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=v=>'TZS '+Number(v||0).toLocaleString('en-TZ',{maximumFractionDigits:2});
function show(msg,error=false){$('pageAlert').textContent=msg;$('pageAlert').className='page-alert'+(error?' error':'')}
async function api(path,options={}){const r=await fetch('/api'+path,{...options,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token,...(options.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch(_){}if(!r.ok)throw new Error(d?.error||'Request failed');return d}
function customerOptions(selected=''){return '<option value="">Select customer…</option>'+customers.map(c=>`<option value="${esc(c.id)}" ${String(c.id)===String(selected)?'selected':''}>${esc(c.name)}</option>`).join('')}
function fillCustomerInfo(){const c=customers.find(x=>String(x.id)===String($('invoiceCustomer').value));$('customerInfo').innerHTML=c?`<strong>${esc(c.name)}</strong><br>${esc(c.address||'')} ${c.phone?'· '+esc(c.phone):''} ${c.email?'· '+esc(c.email):''}`:'Choose a customer.';$('invoiceMachine').innerHTML='<option value="">No machine / general</option>'+(c?.machines||[]).map(m=>`<option value="${esc(m.id)}">${esc([m.model,m.regNumber||m.serialNumber].filter(Boolean).join(' · '))}</option>`).join('')}
function itemRow(item={}){const row=document.createElement('div');row.className='item-row';row.innerHTML=`<input type="hidden" data-field="sparePartId" value="${esc(item.sparePartId||item.spare_part_id||'')}"><label>Part No.<input data-field="partNumber" value="${esc(item.partNumber||item.part_number||'')}"></label><label>Description<input data-field="description" required value="${esc(item.description||'')}"></label><label>Qty<input data-field="quantity" required type="number" min="1" step="1" value="${esc(item.quantity||1)}"></label><label>Unit<input data-field="unit" value="${esc(item.unit||'PC')}"></label><label>Unit Price<input data-field="unitPrice" required type="number" min="0" step="0.01" value="${esc(item.unitPrice||item.unit_price||0)}"></label><button type="button" class="remove-item">×</button>`;row.querySelector('.remove-item').onclick=()=>{if($('invoiceItems').children.length>1)row.remove()};return row}
function resetForm(){ $('invoiceForm').reset();$('invoiceId').value='';$('invoiceSourceJobCardId').value='';$('invoiceDiscount').value='0';$('invoiceVatRate').value='18';$('formTitle').textContent='New Invoice';$('editBadge').classList.add('hidden');$('cancelEditButton').classList.add('hidden');$('saveInvoiceButton').textContent='Save Invoice';$('invoiceCustomer').innerHTML=customerOptions();$('invoiceMachine').innerHTML='<option value="">No machine / general</option>';$('customerInfo').textContent='Choose a customer.';$('invoiceItems').replaceChildren(itemRow({}));}
function editInvoice(id){const inv=invoices.find(x=>String(x.id)===String(id));if(!inv)return;$('invoiceId').value=inv.id;$('invoiceSourceJobCardId').value=inv.sourceJobCardId||inv.source_job_card_id||'';$('formTitle').textContent='Edit '+(inv.invoiceNo||'Invoice');$('editBadge').classList.remove('hidden');$('cancelEditButton').classList.remove('hidden');$('saveInvoiceButton').textContent='Save Changes';$('invoiceCustomer').innerHTML=customerOptions(inv.customer?.id||inv.customerId||'');fillCustomerInfo();$('invoiceMachine').value=inv.machineId||'';$('invoiceDueDate').value=inv.dueDate||'';$('invoiceDiscount').value=inv.discount||0;$('invoiceVatRate').value=inv.vatRate??18;$('invoiceTax').value=inv.tax||0;$('invoiceItems').replaceChildren(...((inv.items?.length?inv.items:[{}]).map(itemRow)));window.scrollTo({top:0,behavior:'smooth'})}
function statusClass(s){s=String(s||'OUTSTANDING').toLowerCase();return s.includes('paid')?'paid':s.includes('cancel')?'cancelled':s.includes('overdue')?'overdue':'outstanding'}
function render(){const q=$('invoiceSearch').value.toLowerCase().trim();const rows=invoices.filter(i=>!q||[i.invoiceNo,i.customer?.name,i.status].join(' ').toLowerCase().includes(q));const pages=Math.max(1,Math.ceil(rows.length/pageSize));if(page>pages)page=pages;const start=(page-1)*pageSize,part=rows.slice(start,start+pageSize);$('invoiceCount').textContent=rows.length;$('pageLabel').textContent=`Page ${page} of ${pages}`;$('prevPage').disabled=page<=1;$('nextPage').disabled=page>=pages;$('invoiceRows').innerHTML=part.length?part.map((i,idx)=>`<tr><td>${start+idx+1}</td><td><strong>${esc(i.invoiceNo||'—')}</strong></td><td>${esc(i.customer?.name||'—')}</td><td>${esc(i.issueDate||i.createdAt||'—')}</td><td>${money(i.total)}</td><td><span class="status ${statusClass(i.status)}">${esc(i.status||'OUTSTANDING')}</span></td><td><div class="actions"><a class="view" href="/api/billing?action=export-invoice&id=${encodeURIComponent(i.id)}&token=${encodeURIComponent(token)}" target="_blank" rel="noopener">View</a><button class="edit" data-edit="${esc(i.id)}">Edit</button><button class="delete" data-delete="${esc(i.id)}">Delete</button></div></td></tr>`).join(''):'<tr><td colspan="7" class="empty-row">No invoices found.</td></tr>';$('invoiceRows').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editInvoice(b.dataset.edit));$('invoiceRows').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteInvoice(b.dataset.delete))}
async function deleteInvoice(id){let confirmation={reason:'Deleted from Invoice Manager'};if(window.belmConfirmDelete){confirmation=await window.belmConfirmDelete({title:'Delete this invoice?',message:'This invoice will move to the Recycle Bin.'});if(!confirmation)return}else if(!confirm('Delete this invoice?'))return;try{await api('/billing/invoices/'+encodeURIComponent(id),{method:'DELETE',body:JSON.stringify(confirmation)});show('Invoice moved to Recycle Bin.');await load()}catch(e){show(e.message,true)}}
async function saveInvoice(e){e.preventDefault();const id=$('invoiceId').value;const items=[...$('invoiceItems').querySelectorAll('.item-row')].map(row=>({sparePartId:row.querySelector('[data-field="sparePartId"]')?.value||'',partNumber:row.querySelector('[data-field="partNumber"]').value.trim(),description:row.querySelector('[data-field="description"]').value.trim(),quantity:Number(row.querySelector('[data-field="quantity"]').value),unit:row.querySelector('[data-field="unit"]').value.trim()||'PC',unitPrice:Number(row.querySelector('[data-field="unitPrice"]').value)}));$('saveInvoiceButton').disabled=true;try{await api(id?'/billing/invoices/'+encodeURIComponent(id):'/billing/invoices',{method:id?'PUT':'POST',body:JSON.stringify({action:id?'edit':undefined,customerId:$('invoiceCustomer').value,machineId:$('invoiceMachine').value||null,sourceJobCardId:$('invoiceSourceJobCardId').value||null,dueDate:$('invoiceDueDate').value||null,discount:Number($('invoiceDiscount').value||0),vatRate:Number($('invoiceVatRate').value||18),tax:Number($('invoiceTax').value||0),items})});show(id?'Invoice updated successfully.':'Invoice saved successfully.');await load();resetForm()}catch(err){show(err.message,true)}finally{$('saveInvoiceButton').disabled=false}}
async function load(){try{const [inv,cust]=await Promise.all([api('/billing/invoices'),api('/billing?action=customer-lookup')]);invoices=Array.isArray(inv)?inv:[];customers=Array.isArray(cust)?cust:[];const current=$('invoiceCustomer').value;$('invoiceCustomer').innerHTML=customerOptions(current);render()}catch(e){show(e.message,true);$('invoiceRows').innerHTML='<tr><td colspan="7" class="empty-row">Could not load invoices.</td></tr>'}}
$('invoiceCustomer').addEventListener('change',fillCustomerInfo);$('addItemButton').onclick=()=>$('invoiceItems').appendChild(itemRow({}));$('newInvoiceButton').onclick=resetForm;$('cancelEditButton').onclick=resetForm;$('invoiceForm').addEventListener('submit',saveInvoice);$('invoiceSearch').addEventListener('input',()=>{page=1;render()});$('prevPage').onclick=()=>{if(page>1){page--;render()}};$('nextPage').onclick=()=>{page++;render()};$('refreshButton').onclick=load;$('logoutButton').onclick=()=>{localStorage.removeItem('belm_admin_token');localStorage.removeItem('belm_admin_user');location.href='/login'};load().then(resetForm);
})();