(function(){
'use strict';
const token=localStorage.getItem('belm_admin_token')||'';
if(!token){location.replace('/login');return;}
let invoices=[],page=1;const pageSize=10;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=v=>'TZS '+Number(v||0).toLocaleString('en-TZ',{maximumFractionDigits:2});
function show(msg,error=false){$('pageAlert').textContent=msg;$('pageAlert').className='page-alert'+(error?' error':'')}
async function api(path,options={}){const r=await fetch('/api'+path,{...options,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token,...(options.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch(_){}if(!r.ok)throw new Error(d?.error||'Request failed');return d}
function statusClass(s){s=String(s||'OUTSTANDING').toLowerCase();return s.includes('paid')?'paid':s.includes('cancel')?'cancelled':s.includes('overdue')?'overdue':'outstanding'}
function render(){const q=$('invoiceSearch').value.toLowerCase().trim();const rows=invoices.filter(i=>!q||[i.invoiceNo,i.sourceProformaNo,i.customer?.name,i.status].join(' ').toLowerCase().includes(q));const pages=Math.max(1,Math.ceil(rows.length/pageSize));if(page>pages)page=pages;const start=(page-1)*pageSize,part=rows.slice(start,start+pageSize);$('invoiceCount').textContent=rows.length;$('pageLabel').textContent=`Page ${page} of ${pages}`;$('prevPage').disabled=page<=1;$('nextPage').disabled=page>=pages;$('invoiceRows').innerHTML=part.length?part.map((i,idx)=>`<tr><td>${start+idx+1}</td><td><strong>${esc(i.invoiceNo||'—')}</strong></td><td>${esc(i.sourceProformaNo||'—')}</td><td>${esc(i.customer?.name||'—')}</td><td>${esc(i.issueDate||i.createdAt||'—')}</td><td>${money(i.total)}</td><td><span class="status ${statusClass(i.status)}">${esc(i.status||'OUTSTANDING')}</span></td><td><div class="actions"><a class="view" href="/api/billing?action=export-invoice&id=${encodeURIComponent(i.id)}&token=${encodeURIComponent(token)}" target="_blank" rel="noopener">Download PDF</a><button class="delete" data-delete="${esc(i.id)}">Delete</button></div></td></tr>`).join(''):'<tr><td colspan="8" class="empty-row">No generated invoices found.</td></tr>';$('invoiceRows').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteInvoice(b.dataset.delete))}
async function deleteInvoice(id){let confirmation={reason:'Deleted from Invoice List'};if(window.belmConfirmDelete){confirmation=await window.belmConfirmDelete({title:'Delete this invoice?',message:'This generated invoice will move to the Recycle Bin.'});if(!confirmation)return}else if(!confirm('Delete this invoice?'))return;try{await api('/billing/invoices/'+encodeURIComponent(id),{method:'DELETE',body:JSON.stringify(confirmation)});show('Invoice moved to Recycle Bin.');await load()}catch(e){show(e.message,true)}}
async function load(){try{const inv=await api('/billing/invoices');invoices=Array.isArray(inv)?inv:[];render()}catch(e){show(e.message,true);$('invoiceRows').innerHTML='<tr><td colspan="8" class="empty-row">Could not load invoices.</td></tr>'}}
$('invoiceSearch').addEventListener('input',()=>{page=1;render()});$('prevPage').onclick=()=>{if(page>1){page--;render()}};$('nextPage').onclick=()=>{page++;render()};$('refreshButton').onclick=load;$('logoutButton').onclick=()=>{localStorage.removeItem('belm_admin_token');localStorage.removeItem('belm_admin_user');location.href='/login'};load();
})();